### ISSUE TITLE
`_git_remote_check:5: = not found`

### ISSUE THREAD

**Issue by creynders** [frmendes/geometry#1]
Hi there, I really like this minimal theme. There's just a small annoyance, whenever I `cd` to a directory with a git repo, it outputs:

``` sh
_git_remote_check:5: = not found
```

**Comment by frm** [comment]
Hey @creynders ! I can't seem to reproduce the issue so I can fix it.

Does it happen on every git repo? Does it happen when the remote isn't set or anything like that?

**Comment by creynders** [comment]
Yes, it happens on every git repo and remote has been set. 

``` sh
△ Projects/iMinds - D-PAC/d-pac.client g remote              master :: 6d :: ⬢
origin
_git_remote_check:5: = not found

 ▲ Projects/iMinds - D-PAC/d-pac.client wd d-pac.cms          master :: 6d :: ⬢
_git_remote_check:5: = not found

 ▲ Projects/iMinds - D-PAC/d-pac.cms g remote                  tests :: 1d :: ⬢
origin
_git_remote_check:5: = not found

 ▲ Projects/iMinds - D-PAC/d-pac.cms                           tests :: 1d :: ⬢
```

Weird...

**Comment by creynders** [comment]
I found the problem, apparently my system doesn't like it if you surround the `=`-signs with spaces.

I.e. L76 throws:

``` sh
if [ $local_commit == $remote_commit ]; then
```

But this won't

``` sh
if [ $local_commit==$remote_commit ]; then
```

**Comment by frm** [comment]
@creynders I was able to reproduce it in an Ubuntu machine. zsh was assuming '==' as "path to =" and outputting not found. I'll be pushing a fix in a moment.

**Comment by creynders** [comment]
👌

**Comment by frm** [comment]
Ok, seems to be it! On my end it seems fine now. Can you confirm this?

**Comment by creynders** [comment]
Confirmed! Thanks!
