### ISSUE TITLE
Cannot configure geometry for single line usage

### ISSUE THREAD

**Issue by safts** [frmendes/geometry#112]
I was looking for a way to configure geometry to a single line prompt, so I tried setting `GEOMETRY_PROMPT_PREFIX=""` but this does not seem to work. I randombly fell on [#102](https://github.com/frmendes/geometry/pull/102)  and specifically on [this line](https://github.com/frmendes/geometry/pull/102/commits/07a810eff33950a49de1c8809daeaa33c56bb553#diff-37d2e8a43274d6fbaf5b762a55f5138cR36). I have very limited zsh knowledge but I guess that this defines `GEOMETRY_PROMPT_PREFIX` to be `$\n` if it is not set. 

By adding it in a configuration file with an empty setting, I guess it is treated as "not set" so it defaults to a new line. 

Is it possible to override this somehow and get a single line prompt?

**Comment by frm** [comment]
Hi! Thanks for reporting.

Did you define `GEOMETRY_PROMPT_PREFIX` *before* loading geometry?

**Comment by safts** [comment]
Yup. I also tried `GEOMETRY_PROMPT_PREFIX="asdf"` and I could see that my prompt took one line and also started with the string "asdf". So I guess the configuration was correctly placed.

**Comment by frm** [comment]
I can't seem to reproduce it. You can see in the two screenshots the settings I use. In the first one, `GEOMETRY_PROMPT_PREFIX` is set to default while the second one overrides the prefix correctly.

<img width="642" alt="screen shot 2017-02-09 at 14 17 11" src="https://cloud.githubusercontent.com/assets/4325027/22786997/a8493bce-eed2-11e6-8b79-5c2569635fe7.png">
<img width="644" alt="screen shot 2017-02-09 at 14 17 50" src="https://cloud.githubusercontent.com/assets/4325027/22786998/a876c878-eed2-11e6-8f74-b3e3cc7a6d2e.png">

**Comment by desyncr** [comment]
@sergafts Yep, that's the problem. It does misplaces "" for unset. If you set it up *after* it will bypass that faulty check. So, there's a workaround.

**Comment by safts** [comment]
Nice! Did the trick. Thank you!
