### ISSUE TITLE
Double empty line as prompt prefix

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#120]
Since this [commit](https://github.com/frmendes/geometry/commit/93dba38ac3db752ca8182c170778499352d66db4) it seems there are two empty lines before the prompt. This only happens on a path without right prompt showing:

```sh
 ▲ ~


 ▲ ~ z geo

 ▲ /storage/Playground/geometry cd


 ▲ ~ 
```

**Comment by desyncr** [comment]
@jedahan We should always create PR even for small things. No need to rush things.

**Comment by jedahan** [comment]
@desyncr I'll make sure to do that in the future
