### ISSUE TITLE
Version tagging

### ISSUE THREAD

**Issue by frm** [frmendes/geometry#121]
Continuing the conversation from #119 :

I think it might be about time to start tagging versions. Then use that to add a deprecation warning like @jedahan said. This means we should start adding a `CHANGELOG` and keep a list of deprecation dates in there.

What do you think of that option?

**Comment by desyncr** [comment]
Deprecation messages at least for now are not that important IMO.

I would start with a minimal `CHANGELOG.md`, and `v0.1.0` then move from that. As of now I think we can go for it.

  - [ ] Create `CHANGELOG.md` with `v0.1.0` entry, just "Initial release" would suffice 
  - [ ] Update README.md with a release badge (see https://img.shields.io/github/release/qubyte/rubidium.svg)
  - [ ] Create release draft in https://github.com/frmendes/geometry/releases, thank our active contributors (castellanprime, ChauTNguyen) and link to https://github.com/frmendes/geometry/graphs/contributors

A future possibility is to have release schedules. But given our codebase and activity it seems unnecessary.

We may automate this but for now this is all we need to release `v0.1.0`.

Thoughts? @frmendes @jedahan

**Comment by frm** [comment]
I'd like to take this on. Start with a minimal version and a `CHANGELOG` and build it up from there.

**Comment by desyncr** [comment]
@frmendes Please do! I'm up for any question.

**Comment by frm** [comment]
@jedahan @desyncr any features you would like to be built upon the implementation of version tagging? We already discussed deprecation messages.

**Comment by jedahan** [comment]
Yeah I think the smallest subset of features for now, until we need them is good. We can probably put all message logic in the setup function on startup for people for now.

**Comment by desyncr** [comment]
@frmendes Is there anything missing to implement versioning? Can I help with anything?

**Comment by frm** [comment]
Well, time for me, tbh. Though, I promise I'll add it tonight 🤞

**Comment by frm** [comment]
Fixed by #146
