### ISSUE TITLE
Extra space when disabling git commit time

### ISSUE THREAD

**Issue by tomspeak** [frmendes/geometry#13]
Recently been using this theme and loving it, this is extremely nit picky, but for such an aesthetic theme it stands out!

If you disable the git time, there's a gap between the spacing where it used to be:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/0I0Z113F3T2r231m2S2y/Image%202016-09-08%20at%2011.44.02%20am.png?X-CloudApp-Visitor-Id=1751005&v=40e46ce8)

Is it possible to make the spacing consistent? Thanks

**Comment by frm** [comment]
It's annoying, yeah. It's even there even when displaying git time, I think. Or maybe my local version has a similar issue. Can you confirm if it happens with git time enabled?

Thanks.

**Comment by tomspeak** [comment]
Ah, you are right, same spacing enabled and disabled.

**Comment by frm** [comment]
I'll push a fix in a bit.

**Comment by frm** [comment]
Done! Seems ok on my end. I'd appreciate if you double checked and feel free to open an issue or submit a PR if you find any other issues.
