### ISSUE TITLE
Allow sourcing plugins from any directory

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#131]
Right now, we default to `$GEOMETRY_ROOT/plugins/$plugin/plugin.zsh`

If we detect that `$plugin` has any `/` in it, maybe we should source that plugin as a full path?

This would help to not need people to clone plugins into `$GEOMETRY_ROOT/plugins/`

**Comment by desyncr** [comment]
Users should not clone their custom plugins into `$GEOMETRY_ROOT/plugins/`, this directory is for built-in plugins.

You can have your custom plugin wherever you want, as long as it register itself with geometry with `geometry_plugin_register` it's all fine.

I don't think geometry should care about how your custom plugins are loaded, or load them (there are other tools for this already).

What do you think @frmendes ?

**Comment by frm** [comment]
I'd rather not make any assumptions on where users should place their plugins. The current solution of letting the user register the plugins is pretty good. That way it's possible to have a bunch of plugins in a `dotfiles/geometry/` directory and have a file source the ones we want registered.

If there's a good reason to change, I'm up for it, but the current solution seems to be the most simple and flexible.

**Comment by jedahan** [comment]
I guess my confusion comes from adding things to `GEOMETRY_PROMPT_PLUGINS`, it seems there are two ways to load geometry prompt plugins, one is registering when sourcing a file, one is using `GEOMETRY_PROMPT_PLUGINS`.  In addition, it seems that to pin a geometry prompt third party plugin, you have to search the codebase for `_GEOMETRY_PROMPT_PLUGINS_PINNED` and add it to that array.

**Comment by desyncr** [comment]
You're right, there are no apis to pin custom plugins. I didn't saw it when reviewing your PR.

I believe that moving [this](https://github.com/frmendes/geometry/blob/master/lib/plugin.zsh#L19) logic inside the `geometry_plugin_register` function would make this functionality available to both built-in and custom plugins.

@jedahan Wanna give it a try? Let me know!
