### ISSUE TITLE
Consider shellcheck

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#136]
I don't know if this is the best one, but [shellcheck](http://www.shellcheck.net/) running on pull requests would be cool for enforcing simple code conventions, like number of spaces, and returning true/false when possible, etc.

**Comment by jedahan** [comment]
Shellcheck does not support zsh https://github.com/koalaman/shellcheck/issues/809

**Comment by desyncr** [comment]
It would be a great addition! Maybe we can push forward to have zsh included in shellcheck, or use ksh? Not sure how alike are those.

**Comment by frm** [comment]
I don't think this is happening anytime soon 😞
