### ISSUE TITLE
prompt_geometry_render:1: = not found

### ISSUE THREAD

**Issue by tomspeak** [frmendes/geometry#14]
I am using `zplug` to manage my plugins, since the update from #13, I now get this error:

`prompt_geometry_render:1: = not found`

I have updated, reloaded my terminal, reloaded zsh and as a last resort re-installed geometry.

Any thoughts? I looked through the code but my understanding is very primitive. Thanks

Variables that I am using:

```
PROMPT_GEOMETRY_GIT_TIME=false
GEOMETRY_COLOR_GIT_DIRTY=9
GEOMETRY_COLOR_GIT_BRANCH=6
GEOMETRY_COLOR_EXIT_VALUE=9
PROMPT_GEOMETRY_GIT_CONFLICTS=true
GEOMETRY_SYMBOL_EXIT_VALUE="▲"
```

**Comment by frm** [comment]
What version of zsh are you using?

**Comment by tomspeak** [comment]
```
zsh --version
zsh 5.2 (x86_64-apple-darwin15.6.0)
```

```
zplug --version
2.2.0
```

**Comment by frm** [comment]
I'm not able to reproduce your issue using antibody. But can you check if it's fixed now?

**Comment by tomspeak** [comment]
Works perfectly, thanks for the fix. Great theme :)

**Comment by frm** [comment]
Wow, that was a blind guess. Super! Thanks for using!
