### ISSUE TITLE
Create a CONTRIBUTING.md document

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#148]
- Define code conventions
- Create plugin template

**Comment by hs256** [comment]
@desyncr ..I will like to work on this and this will be my first contribution in open-source.

**Comment by frm** [comment]
Great! If you need any help, let us know!

**Comment by desyncr** [comment]
@harshaiitr Awesome!

There are [plenty](https://github.com/search?q=CONTRIBUTING.md&ref=opensearch) of CONTRIBUTING.md documents out there to checkout and take ideas from.

Remember to create a PR with your changes as soon as you start to work, so we can work together.
Any help you need where are here or in [gitter](https://gitter.im/geometry-zsh/Lobby).

**Comment by desyncr** [comment]
@harshaiitr Do you need any help? Let me know how it's going :)

**Comment by shridharmanvi** [comment]
Here is a [PR](https://github.com/geometry-zsh/geometry/pull/178) for this one.

**Comment by frm** [comment]
Closed by #178
