### ISSUE TITLE
ERR: Error stat()ing when dealing with a rebase with conflicts

### ISSUE THREAD

**Issue by tomspeak** [frmendes/geometry#150]
```
 λ Sites/test ERR: Error stat()ing: files/test.jsx
ERR: Error opening directory  files/test.jsx: No such file or directory

 λ Sites/test                                                                                                             8s  ⇡ 2675b08b ◆ :: 2d :: ⬡
```

When I do `git pull --rebase origin master`, and incur conflicts, this will be printed in the console after each command is ran. `ls`, `cd` and what not.

Is this related to geometry?

**Comment by desyncr** [comment]
It does seems like a custom error from somewhere else. I'll take a further look later today.

Thanks for reporting.

**Comment by tomspeak** [comment]
Cheers, I am going to comb through my setup later to see if I can identify anything that would conflict. I run a pretty light setup so I thought I'd start here at least.

**Comment by frm** [comment]
Oh. I think I know what this is. It's when you have conflicts in a file and in that same commit some other file was removed. It tries to open all changed files in that commit to count the conflicts.

I can tackle this later today.

**Comment by desyncr** [comment]
This happens during a conflict on a non top-level directory due to `git diff --name-only --diff-filter=U` in `prompt_geometry_git_conflicts`.
