### ISSUE TITLE
How to make a custom auto-ls function by enter key and geometry theme workable together?

### ISSUE THREAD

**Issue by kreedz** [frmendes/geometry#151]
Auto-ls function, actually two functions that I found, they works fine for example with oh-my-zsh arrow theme.
function one:
```
auto-ls () {
   if [[ $#BUFFER -eq 0 ]]; then
       echo ""
       ls
       zle redisplay
   else
       zle .$WIDGET
   fi
}
zle -N auto-ls
zle -N accept-line auto-ls
zle -N other-widget auto-ls
```

function two:
```
function do_enter() {
    if [ -n "$BUFFER" ]; then
        zle accept-line
        return 0
    fi
    echo
    ls
    if [ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" = 'true' ]; then
        echo
        echo -e "\e[0;33m--- git status ---\e[0m"
        git status -sb
    fi
    zle reset-prompt
    return 0
}
zle -N do_enter
bindkey '^m' do_enter
```
I'm putting function after loading theme.

But with geometry theme I just can see for like 0.1 second the output of ls when hitting enter and then it disappear. I've just find out that it happens when ls output has one line.
But if there more than one line, in that case hitting enter gives ls output without last line.
And I can't navigate without cd now. So when I entering directory name without cd than I getting 'command not found'.

**Comment by desyncr** [comment]
You may try disabling async: `PROMPT_GEOMETRY_RPROMPT_ASYNC=0`

**Comment by kreedz** [comment]
It gives nothing except ```prompt_geometry_render:12: command not found: 0``` when performing any command.

**Comment by desyncr** [comment]
Sorry, it should be `PROMPT_GEOMETRY_RPROMPT_ASYNC=false`.

**Comment by kreedz** [comment]
Now it gives nothing too.

**Comment by desyncr** [comment]
Can confirm the issue is present in `master`. I'll further investigate it.

**Comment by desyncr** [comment]
Tried `auto-ls` and found the issue has to do with `GEOMETRY_PROMPT_PREFIX`.

There are two workarounds for this:

- Set `GEOMETRY_PROMPT_PREFIX` to "".

```
GEOMETRY_PROMPT_PREFIX=""
```

- Adapt `auto-ls` function:

```
auto-ls () {
   if [[ $#BUFFER -eq 0 ]]; then
       echo ""
       ls
       echo "" # Workaround
       zle redisplay
   else
       zle .$WIDGET
   fi
}
```

I haven't tried `do_enter` function but it should be a similar issue. I have still have to understand why this happens.

**Comment by kreedz** [comment]
Thanks, both workarounds works well.

While googling I found on [SO](http://stackoverflow.com/questions/30169090/zsh-behavior-on-enter) some little information:
> While it would be sufficient to run zle accept-line only in cases where there actually was a command, zsh would not put a new prompt after the output. And while it is possible to redraw the prompt with zle redisplay, this will probably overwrite the last line(s) of the output if you are using multi-line prompts. (Of course there are workarounds for that, too, but nothing as simple as just using zle accept-line.

**Comment by desyncr** [comment]
Thanks for the link. Good info :+1:
