### ISSUE TITLE
Coordinate hangout on Gitter

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#156]
Let's coordinate a date and time to chat about the project on [gitter](https://gitter.im/geometry-zsh/Lobby).

Main topic is: Announcing releases on various zsh-related sites, etc. See https://github.com/fribmendes/geometry/pull/146#issuecomment-292571915

RSVP @jedahan @fribmendes 

Time frame will be about 30-60 min. Everyone is welcome!

**Comment by desyncr** [comment]
Next week I'm available around 16:00 hs UTC.

**Comment by frm** [comment]
I'm on vacation this week. Next week is pretty much fine for me.

**Comment by desyncr** [comment]
We may schedule [`Tuesday May 23, 16:00 UTC`](https://time.is/compare/1600_23_May_2017_in_UTC)? @jedahan Are you joining?

Edit: Updated day

**Comment by frm** [comment]
Perfect for me.

**Comment by jedahan** [comment]
I'll be there!

**Comment by desyncr** [comment]
Awesome. Gonna send reminders -somehow- later today.

**Comment by frm** [comment]
@desyncr did you mean Tuesday 23rd or Thursday 25th?

**Comment by desyncr** [comment]
Tuesday 23rd, my bad.

**Comment by frm** [comment]
Just a PSA: everyone is free to jump in on the discussion/hangout :heart:

**Comment by desyncr** [comment]
Hangout was a success! We discussed various topics and coordinated a bunch of work to do.

- Take a look at the hangout [wiki page](https://github.com/fribmendes/geometry/wiki/Gitter-hangout-23-05) where we put most of the hangout definitions and tasks
- You should take a look at our brand new [Trello board](https://trello.com/b/GfM4e6Ro/geometry)
- Or review the [chatlogs](https://gitter.im/geometry-zsh/Lobby?at=592457cdeec422e415df7bee)

Thanks all for joining in!

**Comment by desyncr** [comment]
Closing this now.

**Comment by frm** [comment]
I'd like to suggest a new hangout to discuss announcements on different channels. Say, Thursday, June 8, 16h00 UTC? 30-45min

Also, should we keep an ongoing issue to discuss the next hangout?

**Comment by desyncr** [comment]
I'll open up a new issue.

**Comment by jedahan** [comment]
It boggles my mind that time.is doesn't have add to calendar links for popular calendar services

**Comment by desyncr** [comment]
Trello does have a calendar integration (google calendar, ical AFAIK). Last time I checked I didn't found any community/open calendar service :/
