### ISSUE TITLE
command not foud: async_job

### ISSUE THREAD

**Issue by wodinga** [frmendes/geometry#157]
I keep getting 
```

-geometry-async-job:1: command not found: async_flush_jobs
-geometry-async-job:2: command not found: async_job
```

on every prompt. How should I fix this? I installed it manually.

**Comment by desyncr** [comment]
Do:

    cd <geometry_path>
    git submodule update --init

**Comment by wodinga** [comment]
I did it and I'm still getting

`/home/boop/.oh-my-zsh/themes/geometry-master/lib/async.zsh:source:1: no such file or directory: /home/boop/.oh-my-zsh/themes/geometry-master/lib/zsh-async/async.zsh
geometry_async_setup:1: command not found: async_init
geometry_async_setup:3: command not found: async_start_worker
geometry_async_setup:4: command not found: async_register_callback
-geometry-async-job:1: command not found: async_flush_jobs                      
-geometry-async-job:2: command not found: async_job`

**Comment by desyncr** [comment]
What's the output from `git submodule update --init`? Can you copy and paste it?

**Comment by wodinga** [comment]
`▲ .oh-my-zsh/themes/geometry-master git submodule update --init

-geometry-async-job:1: command not found: async_flush_jobs                      
-geometry-async-job:2: command not found: async_job`

**Comment by desyncr** [comment]
Alright, I think what the issue could be. Try pulling latest changes from geometry:

    git fetch --all
    git pull
    git submodule update --init

**Comment by wodinga** [comment]
` ▲ .oh-my-zsh/themes/geometry-master git fetch --all
Fetching origin
-geometry-async-job:1: command not found: async_flush_jobs                      
-geometry-async-job:2: command not found: async_job

 ▲ .oh-my-zsh/themes/geometry-master git pull
Already up-to-date.
-geometry-async-job:1: command not found: async_flush_jobs                      
-geometry-async-job:2: command not found: async_job

 ▲ .oh-my-zsh/themes/geometry-master git submodule update --init
-geometry-async-job:1: command not found: async_flush_jobs                      
-geometry-async-job:2: command not found: async_job
`

**Comment by desyncr** [comment]
Do you open another shell and the issue persists? If so, could you try to re-install it?

**Comment by wodinga** [comment]
Hm.... I'm not sure if I had cloned it, so that's why i don't think any git commands were working right. Seems to be working now!

**Comment by desyncr** [comment]
:+1: Awesome! Thanks!
