### ISSUE TITLE
prompt_geometry_set_cmd_title:  backticks and $() get evaluated twice

### ISSUE THREAD

**Issue by fth86** [frmendes/geometry#16]
Over at oh-my-zsh we just confirmed the geometry theme to be responsible for the double evaluation of commands within backticks and $():

$ echo `echo doh >> doh`
$ cat doh
doh
doh

The same happens with $(). mcornella was able to trace it to:

prompt_geometry_set_cmd_title () {
        prompt_geometry_print_title "${2} @ %m"
}

When I set that function to {}, the problem disappears.

**Comment by frm** [comment]
Thanks! I can reproduce it and working on it.

Is there an issue where that was discussed?

**Comment by fth86** [comment]
No issues.  Thanks for fixing, I like your theme!

**Comment by frm** [comment]
I was actually asking if you had opened up an issue at the oh-my-zsh repo. I see it's been opened [here](https://github.com/robbyrussell/oh-my-zsh/issues/5466)

Just pushed a quick hack to have this work. Even though it's not exactly the prettiest solution. Can you double check to see if it's fixed on your end?

**Comment by fth86** [comment]
it worked
