### ISSUE TITLE
Virtualenv not showing

### ISSUE THREAD

**Issue by Threynaud** [frmendes/geometry#161]
Hi,

First thank you you for this theme, I really love it!!

However I have a problem with the virtualenv plugin that doesn't seem to work at all for me.

I have added the plugin in my `.zshrc` before loading geometry:
```
export GEOMETRY_PROMPT_PLUGINS=(exec_time git jobs virtualenv)
ZSH_THEME="geometry/geometry"
```
Nothing is showing in my terminal when a virtualenv is activated:
```
echo $VIRTUAL_ENV
>>> /Users/thms/.virtualenvs/venv_test
```
Doing `export GEOMETRY_PROMPT_PLUGINS=(exec_time git jobs +virtualenv)` displays empty parenthesis where the venv should be showing that the plugin is loaded.

I can't find any setting that could pose a problem..

Thanks for your help!

**Comment by kevin940726** [comment]
Maybe not related, but `exec_time` is also broken. Probably related to #160 as I'm pretty sure the problem is in `zsh-async` (I've been able to make it work by reverting it back to v1.0.0).

**Comment by desyncr** [comment]
Related to https://github.com/fribmendes/geometry/pull/160

**Comment by desyncr** [comment]
@kevin940726 @Threynaud It should be solved in master.

Any feedback is welcome!

**Comment by Threynaud** [comment]
Working great indeed, thanks a lot!

**Comment by desyncr** [comment]
Awesome! Thanks for reporting.

Closing.
