### ISSUE TITLE
Help people update their references from frmendes to fribmendes

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#162]
https://github.com/search?langOverride=&q=frmendes%2Fgeometry&repo=&start_value=1&type=Code

shows 110 references.
Would be nice to find a bot or just make one, that checks if the latest version of that file exists, and creates a pull request to update it to fribmendes/geometry.

This could also be a kind of invitation for soliciting feedback, or a gentle intro to say hi.

**Comment by frm** [comment]
We should also update the references along the repo.

**Comment by frm** [comment]
Can I take this?

If we are changing to an org, might as well do it all together.

I'm thinking of scripting something to comment on files of users with `frmendes/geometry` on GitHub but that might be over-engineering this. Any other ideas?

**Comment by desyncr** [comment]
It depends on how many repos we want to address. Less than 100 can be manually. Any number greater  than that would require to automate it (see https://developer.github.com/v3/issues/#create-an-issue).

I think addressing all appearances will be optimal. Github gem is not too complex anyways.

**Comment by frm** [comment]
This is on geometry-zsh now. GitHub redirects everything. I can simply add two repos in my accounts that sync with this one but print out a deprecation warning, if that's ok with you guys.

**Comment by desyncr** [comment]
Seems overkill to me. I'd rather just stay with github redirects.

**Comment by frm** [comment]
Closing it then.
