### ISSUE TITLE
Add project's Trello link/badge

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#163]
Add either a link or a badge to our [Trello board](https://trello.com/b/GfM4e6Ro/geometry) in the `README.md`.

Should be a good task for a First Pull Request or for anyone who wants to contribute.

**Comment by morrme** [comment]
Says "board not found" but it may be that I do not have access.

**Comment by desyncr** [comment]
Sorry, it was configured to be "Team visible" made it public. @fribmendes

**Comment by frm** [comment]
Ups, my bad.

**Comment by desyncr** [comment]
ex:

![](https://img.shields.io/badge/Trello-board-blue.svg)

**Comment by desyncr** [comment]
Fixed with #173
