### ISSUE TITLE
Geometry Logo Contest [Draft]

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#164]
Geometry deserves a logo!

Submit logo designs by replying to this issue, one comment per submission.

Vote on logos by reacting with 👍, all other reactions will be ignored.

We will be closed for submissions and votes on [April 24th, 00:00 UTC](https://time.is/compare/0000_24_Apr_2017_in_UTC).

If the top voted logo has 50% more votes than second place, we will use that.

Otherwise, @fribmendes, @desyncr and @jedahan will decide between the top 3 submissions.

Everyone who contributes a submission will be thanked in our readme.

# logos

**Comment by jedahan** [comment]
I wrote this to start a discussion. We can decide when to really open it for submissions and how to announce it.

**Comment by frm** [comment]
I temporarily added a very simple logo to the organization, but if any suggestions come along we're up for it 😄

**Comment by MarioRicalde** [comment]
I can work on this.

**Comment by MarioRicalde** [comment]
I'm going to make some proposals and post them here, and then we can pick it up.

**Comment by MarioRicalde** [comment]
@jedahan @justmendes here's one.

![image](https://user-images.githubusercontent.com/125900/52896344-3ff95c80-318c-11e9-8f3d-b55aafd6c0da.png)

**Comment by MarioRicalde** [comment]
I did this super quickly so it's pretty much a draft still,  but let me know if you like the direction. Based it off the one we currently have thanks to @jedahan .

Cheers.

**Comment by MarioRicalde** [comment]
@justmendes @jedahan any feedback here? should it be geometry.zsh ?

**Comment by jedahan** [comment]
I love the colors, capitalization, and overlapping triangles. I think it also allows for derivatives that make sense in different contexts if we really want (like a smaller flat version, etc).

i wish i could be more critical but its quite beautiful

**Comment by jedahan** [comment]
maybe experimenting with fonts that are more geomrtric like where the O is a perfect circle?

**Comment by MarioRicalde** [comment]
@jedahan thank you for the positive feedback, do we want to keep using monospaced fonts or any font fits as long as it's the O as a perfect circle?

**Comment by jedahan** [comment]
i love the yellow its bright and sun-like

maybe trying a different colorscheme from blue/red if it's a bit similar to google play? like instead of red/blue up top a purple?

i hope this is useful feedback but im mostly stretching

**Comment by frm** [comment]
I love the details of having the sides of the larger triangle with different colours to give a "3D impression", so to speak. Love the overlap as well.

Agree with @jedahan regarding the colorscheme.

I'd go for a monospace font, personally. They're related to code, by nature. But don't overthink it too much. I'd prefer if we had a version without any text as well. For the GitHub org and stuff like that, where the text doesn't really matter that much or is hard to read.

**Comment by jedahan** [comment]
Is the current font monospace? I like its look regardless, and am happy for us to have non-monospace font, as there is plenty of monospace in other reading materials and tech projects.
Really I see this version as a banner for our readme. Would be interested in seeing how this would fit, for example, as the geometry-zsh organization icon, with and without geometry text.

**Comment by MarioRicalde** [comment]
I'm going to do a bit of work on this, I'm a bit limited on time today, but here's the link where I'm working on it. If you want a live version, just click on it.

https://www.figma.com/file/gx1IWp28K1mlyl2YfYJJA51l/geometry?node-id=0%3A1

**Comment by MarioRicalde** [comment]
![image](https://user-images.githubusercontent.com/125900/52973726-a1841b80-3384-11e9-8c31-41fa9bb1b17d.png)

Thanks for the feedback. The font I was using above was monospaced. I believe it was Fira? Regardless, I prefer non-monospace fonts for what we have here, because I like that slick look we get from non-monospaced fonts. 

If you guys are sold on the colors on the above, I can make all the assets we need. README, Org Image, etc. Just let me know any sizes you want.

**Comment by MarioRicalde** [comment]
@jedahan @justmendes Thoughts?

**Comment by MarioRicalde** [comment]
![image](https://user-images.githubusercontent.com/125900/52973909-5d454b00-3385-11e9-98da-e761c9fd6d23.png)

I like the contrast that comes from the accented background.

**Comment by MarioRicalde** [comment]
![image](https://user-images.githubusercontent.com/125900/52973997-a4cbd700-3385-11e9-9a2b-5a5dab57ad8c.png)

**Comment by MarioRicalde** [comment]
![image](https://user-images.githubusercontent.com/125900/52974185-50752700-3386-11e9-8852-955495f732bd.png)

And my last proposal for now. Awaiting feedback.

**Comment by jedahan** [comment]
Great changes!
I like the background glow of the last one a lot.
As far as the new font goes, does it look alright in a heavier weight like the original?
Either way the main assets I can think of are a text-less version for the geometry-zsh org, and a header version for the readme.

**Comment by MarioRicalde** [comment]
![image](https://user-images.githubusercontent.com/125900/52974951-02adee00-3389-11e9-84a8-b06709f2e785.png)

@jedahan thoughts? :)

**Comment by jedahan** [comment]
Beautiful, ship it!

**Comment by MarioRicalde** [comment]
Shipped, here's the zip and previews [geometry.zip](https://github.com/geometry-zsh/geometry/files/2877395/geometry.zip)

![readme-logo](https://user-images.githubusercontent.com/125900/52976330-bb2a6080-338e-11e9-9f11-c8e2b0ad510c.png)

![thumbnail-solo](https://user-images.githubusercontent.com/125900/52976331-bcf42400-338e-11e9-87ea-302c9ff70676.png)

![thumbnail-text](https://user-images.githubusercontent.com/125900/52976332-be255100-338e-11e9-930e-121e61bf88b1.png)

**Comment by frm** [comment]
This is awesome! Thanks! Updating the org.

**Comment by MarioRicalde** [comment]
@frm do you reckon I could get some love in the README for the logo? That'd be great! Just a mention to my github would be good. Thank you!

**Comment by jedahan** [comment]
@MarioRicalde credit applied! Sorry we didn't have this in sooner!

**Comment by MarioRicalde** [comment]
@jedahan thank you! Happy holidays!
