### ISSUE TITLE
Gitter hangout 2nd Edition

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#167]
Let's coordinate a date and time to chat about the project on gitter.

Main topic is: Announcements on different channels, etc. See https://github.com/fribmendes/geometry/issues/156#issuecomment-306153576

RSVP @jedahan @fribmendes

Proposed date and time: [Thursday, June 8, 16h00 UTC](https://time.is/compare/1600_8_June_2017_in_UTC)
Time frame will be about 30-45 min. Everyone is welcome!

**Comment by frm** [comment]
Yes pls.

Also, can we update this issue for future hangouts? Or maybe propose on Trello.

**Comment by desyncr** [comment]
You mean a template for hangout announces?

**Comment by desyncr** [comment]
BTW I'm up for Thursday, June 8, 16h00 UTC.

**Comment by frm** [comment]
I mean having an issue just to set up Gitter hangouts. Instead of creating one for each individual hangout. Although that might be less spammy if we use Trello.

**Comment by desyncr** [comment]
Problem is no one will know except us. I like the issue-tracker approach as you can easily Watch or Unwatch the repo to see what's going on, including hangouts. Not sure you can follow a Trello board.

May be coordinate on the Trello board and announce on the github issue-tracker?

**Comment by frm** [comment]
Sounds reasonable to me.

**Comment by desyncr** [comment]
Another good Hangout!

We coordinated a bunch of work to do for our next announcement.

- Take a look at the hangout [wiki page](https://github.com/fribmendes/geometry/wiki/Gitter-hangout-2017-06-08)
- You should take a look at our brand new [Trello board](https://trello.com/b/GfM4e6Ro/geometry)
- Or review the [chatlogs](https://gitter.im/geometry-zsh/Lobby?at=5939739e142826e97296ca9b)

Thanks all for joining in!

**Comment by desyncr** [comment]
Closing this now!
