### ISSUE TITLE
Create feature screencasts: git prompts

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#168]
As per: https://trello.com/c/Z6rm05JG/10-create-feature-screencasts

- [x] Display basic git prompt (branch, days since commit, repo clean/dirty)
- [ ] Display git conflicts

## Optional

- [ ] Long and short time format
- [x] 'No commits' message
- [x] Unpulled/unpushed

**Comment by jedahan** [comment]
Heads up, expect v1 this weekend

**Comment by jedahan** [comment]
v1 is here! [![asciicast](https://asciinema.org/a/8fNQ2Knqw2LXD9O649x9sw7EN.png)](https://asciinema.org/a/8fNQ2Knqw2LXD9O649x9sw7EN)

**Comment by jedahan** [comment]
OK so this is more like alpha. 5s is too short. Want to reduce the total time to under 30s

## improvements for beta
- remove the nonzero exit code stuff
- remove the incorrect git commit then git add
- combine the "mkdir screencast && cd $_"
- set the upstream so we see the conflict arrows asap

**Comment by desyncr** [comment]
Nice work! Set up and speed is good. I agree regarding removing incorrect commands.

Keep up the good work!

**Comment by frm** [comment]
I really like the inline explanations ❤️ 

Agree with the improvements. I wonder if we can add a `git rebase origin/master` the rebase in progress symbol. Or even the conflict count. Or is that too much for a single screencast?

**Comment by jedahan** [comment]
So new 'script', which will be about 60s long
```zsh
# geometry git features
mkdir screencast
cd $_
git init
echo “#hi there” > readme.md
git add readme.md
git commit -m ‘initial readme’
# time is how long since last commit
git remote add origin git@github.com:jedahan/screencast.git
# up arrow means we have unpushed changes
git branch -u origin master
# down arrow means we have unpulled changes
git push -u origin master
# there are more indicators, like ◈ conflicts and  rebases
# ▲ thanks for watching ▲
```

**Comment by jedahan** [comment]
Second version, much shorter

[![asciicast](https://asciinema.org/a/FNwUhhcHJzdMIUb2D1otBowcz.png)](https://asciinema.org/a/FNwUhhcHJzdMIUb2D1otBowcz)

**Comment by jedahan** [comment]
![geometry-git](https://user-images.githubusercontent.com/32407/29006139-f93d2dc6-7ab7-11e7-9b34-a16ea909a1fd.gif)

gif version that can just be embedded :)

**Comment by desyncr** [comment]
Looking really good to me.

We'll have to do a bit of a recap as we've lost track of progress. @jedahan @fribmendes

**Comment by jedahan** [comment]
hmm looks like the cool icons didnt render in the gif :/

**Comment by frm** [comment]
Looks good!

Yeah, we should do a recap and regroup. Should we schedule a new gitter hangout?

**Comment by desyncr** [comment]
@fribmendes I'm up for it. Just set up a date and I'll be there.

**Comment by frm** [comment]
Is it possible this week for you guys? Let's say Wednesday 2.30PM BST?

**Comment by desyncr** [comment]
For me OK.

**Comment by jedahan** [comment]
works fine for me

**Comment by frm** [comment]
Final version: ![](https://user-images.githubusercontent.com/32407/29006139-f93d2dc6-7ab7-11e7-9b34-a16ea909a1fd.gif)

Cheers to @jedahan!
