### ISSUE TITLE
Create feature screencasts: exec time / exit status / background jobs

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#169]
As per: https://trello.com/c/Z6rm05JG/10-create-feature-screencasts

- [ ] Display execution time command
- [ ] Diplay exit status symbol
- [ ] Display background job symbol/count

**Comment by jedahan** [comment]
Just a note, working on this over the weekend :)

**Comment by frm** [comment]
Final version: ![](https://user-images.githubusercontent.com/32407/29006139-f93d2dc6-7ab7-11e7-9b34-a16ea909a1fd.gif)

Cheers to @jedahan!
