### ISSUE TITLE
git_conflicts issue since zplug 2.3.1

### ISSUE THREAD

**Issue by tomspeak** [frmendes/geometry#17]
Hi,

Updated to zplug `2.3.1`, and since then have had lots of issues with zsh, there is also this issue, where the theme is not displayed, but this error keeps appearing:

`prompt_geometry_git_conflicts:[:10: integer expression expected: 1\n1`

I have an issue posted (here, for some more information)[https://github.com/zplug/zplug/issues/268]

Do you know if this is anything caused on your end, or a symptom of a larger issue?

**Comment by desyncr** [comment]
Try
- Loading geometry theme without zplug loaded
- Loading zplug with other theme (with git integration - say agnoster)

With that information you'll have an idea where the issue is.

**Comment by frm** [comment]
The `prompt_geometry_git_conflicts:[:10: integer expression expected: 1\n1` has happened to me previously, so I'll look into it when I can reproduce it. If you want to open a different issue, I'd really appreciate it.

The zplug thing, would you be able to try what @desyncr said?

**Comment by tomspeak** [comment]
I switched over to antibody and all issues seem to have been cleared up!

**Comment by tomspeak** [comment]
Spoke too soon. It just popped up again during a git rebase.

I am now using an identical setup to your antibody one, @frmendes.

**Comment by frm** [comment]
Is it working with antibody?

**Comment by tomspeak** [comment]
The theme and zsh works flawlessly, other than the git conflict warning posted above appearing during rebases.

**Comment by frm** [comment]
Yea, I'll try to reproduce that. Happened to me during a rebase, but it doesn't happen consistently.

**Comment by tomspeak** [comment]
Seems to be fully functional, just pointing it out incase it's a symptom of something bigger.

**Comment by jimmyharris** [comment]
I am seeing the same issue with zplug version 2.2.0 I believe the issue was introduced with the with the recent timestamp prompt enhancement because checking out c8ec1b6 seems to have made the issue go away.

**Comment by tomspeak** [comment]
Just to note, I have this consistently on every rebase that has conflicts these days. I'm fully up to date with antibody and this theme.

**Comment by desyncr** [comment]
I'll take a look into this later tonight.

**Comment by desyncr** [comment]
Can't seem to be able to reproduce it.

**Comment by frm** [comment]
I ran into this yesterday at work during multiple rebases. But it doesn't seem to happen everytime and I am not able to reproduce it consistently.

**Comment by desyncr** [comment]
Looking further it seems you have to have at least two merge conflicts during a rebase.

Issue I'm facing though is [here](https://github.com/frmendes/geometry/blob/master/geometry.zsh#L185) it's failing to determine `total`:

```
▲ ~ echo $conflicts
README.md
source.c

▲ ~ grep -c '^======$' $conflicts
grep: README.md
source.c: No such file or directory

▲ ~ grep -c '^======$' README.md source.c
README.md:0
source.c:0
```

**Comment by frm** [comment]
It's a bit worse than that because `file_count=$(echo -n "$conflicts" | $GREP -c '^')` returns different results for `grep` and `ag`.

``` zsh
 ▲ ~/Developer/geometry-test echo -n "$conflicts" | grep -c '^'
2

 ▲ ~/Developer/geometry-test echo -n "$conflicts" | ag -c '^'
1
1
```
