### ISSUE TITLE
Reconsider gitter

### ISSUE THREAD

**Issue by frm** [frmendes/geometry#176]
As mentioned during the gitter hangout, I'm questioning if we should continue to use gitter or move to a new platform.

Gitter is a great entry point for users and contributors, but we're barely there idling. So if a new user or contributor comes up, we won't notice it.

After speaking with @desyncr about it, there are two good options. Slack or IRC.

Slack requires registering and is a lot more bloated. We don't need any integrations and we just need a single room. It's also very eager on resources.

Good old IRC doesn't need no registration, we can just add a link to web IRC for users that are unfamiliar with it and we can easily idle there. It also has more adoption than gitter.

I'd like to hear more takes on this before making any decision.

/cc @desyncr @jedahan

**Comment by jedahan** [comment]
I love irc, but these days am more active on slack.
Downside of slack is we would probably want to make a slackin instance so people can just put in their email and get invited.
Sucks that I missed the meeting yesterday, which definitely is a side effect of my lack of idling on gitter.
And sucks that gitter.im isn't working out as well, as it seems to solve these features well. I think the tab gets swallowed in my browser. Maybe using a gitter wrapped 'native' client would help with the idling/realtime issue...

**Comment by frm** [comment]
I also use Slack more, but the fact that it's so bloated and a pain to add users, makes me a bit sceptical regarding using it for this.

I use a gitter client but it's no use, tbh. It doesn't have as much active users and it's much of a pain to iddle in. I need to have the gitter client running at all times, instead of using a bouncer on a server and being occasionally notified like on IRC. That's my favorite option.

I've also been finding gitter a bit less intuitive and "closed" - maybe not the best word to describe it, but the process of joining in is just a bit harder than IRC.

**Comment by frm** [comment]
@desyncr what's your take on this?

**Comment by desyncr** [comment]
I'm up for IRC. Slack is team-centric rather than an open channel for anyone to jump in.

IRC+WebIRC would be a good alternative to gitter.

**Comment by frm** [comment]
I'm willing to idle on IRC for a while, for now. And see how it goes. Is everyone ok with freenode?

**Comment by frm** [comment]
#geometry-zsh on freenode is now available! 🎉
