### ISSUE TITLE
Have to source zshrc to use some environment variables

### ISSUE THREAD

**Issue by mustaqimmalim** [frmendes/geometry#179]
This has bugged me for a while. I have to run `source .zshrc` to get the `PROMPT_GEOMETRY_COLORIZE_ROOT` to show correctly.

**Comment by frm** [comment]
Are you setting the variable before sourcing geometry?

**Comment by mustaqimmalim** [comment]
At last I found out why, I had to change permissions to `~/.zplug` and now it works correctly. Sorry for the bother.
