### ISSUE TITLE
How to change terminal's title bar color to dark

### ISSUE THREAD

**Issue by wyudong** [frmendes/geometry#180]
I can't find any way to change the terminal's title bar color to dark, just shown in the screenshot. Is that also possible for Mac's default terminal?

<img width="795" alt="2017-10-07 14 41 56" src="https://user-images.githubusercontent.com/5687273/31305514-0e8cd61c-ab01-11e7-87c7-89c69ab3616c.png">

**Comment by frm** [comment]
That's iTerm 2 dark theme. I'm not familiar with Terminal.app's settings, to be honest, but I don't think you can.
