### ISSUE TITLE
Hangout - 4th Edition

### ISSUE THREAD

**Issue by frm** [frmendes/geometry#182]
So, this was kind of stalled for a while. Personally, I got caught up with a lot of work and ended up halfway into a burn out.

I'm proposing a new hangout. Not on Gitter but on IRC. I'll create an appropriate channel and post it here.

Topics:

* Marketing
* Subtheming (as marketing)
* Project complexity
* Issue review
* Trello review

**Date:** Thursday, Oct 26, 2 PM GMT.

Please RSVP @desyncr @jedahan

**Comment by jedahan** [comment]
I can do 9am EST oct 26th

**Comment by frm** [comment]
Sounds good to me. That's 1PM GMT for anyone else.

**Comment by frm** [comment]
PSA: This will happen on the #geometry-zsh channel on freenode.

**Comment by jedahan** [comment]
gah, I slept in :(

**Comment by frm** [comment]
@jedahan no worries, would you like to suggest a new date and time?

**Comment by frm** [comment]
Everyone seems to be back on board, can we go with [2PM GMT](https://time.is/1400_29_Nov_2017_in_GMT/EST)? It's 9AM EST if you are still in that timezone @jedahan 😄 

RSVP @jedahan @desyncr

**Comment by desyncr** [comment]
I'm up for it.

**Comment by jedahan** [comment]
I'm actually in Berlin now, so that is 3pm here, I can make that!

**Comment by frm** [comment]
On this topic: https://github.com/blog/2471-introducing-team-discussions

I suggest we try it.

**Comment by frm** [comment]
Do we agree on using team discussions and not the issues? 😄

**Comment by desyncr** [comment]
Yes, indeed.
