### ISSUE TITLE
Adding Node and Exec Time to the terminal

### ISSUE THREAD

**Issue by designMoreWeb** [frmendes/geometry#183]
I am still confused how to add the node and exec_time plugins to the terminal so it displays them.

**Comment by frm** [comment]
You can simply add `GEOMETRY_PROMPT_PLUGINS=(node exec_time)` to your `.zshrc` before sourcing geometry.

Note that this will override the set of default plugins (`exec_time`, `git`, `hg`, `jobs`). You can add the ones you like through that variable (e.g. `GEOMETRY_PROMPT_PLUGINS=(node exec_time git)`)

**Comment by designMoreWeb** [comment]
i added that but its still not showing in the terminal 

 #Set name of the theme to load.
 export PATH="/Users/Divster/anaconda/bin:$PATH"
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

GEOMETRY_PROMPT_PLUGINS=(node exec_time git)

#ZSH_THEME="obraun"
#ZSH_THEME="cobalt2"
#ZSH_THEME="agnoster" # (this is one of the fancy ones)
#ZSH_THEME="honukai"
#ZSH_THEME="lambda-pure"
 ZSH_THEME="geometry/geometry"

**Comment by frm** [comment]
Can you try with `export` before the variable?

**Comment by designMoreWeb** [comment]
i put export before GEOMETRY_PROMPT_PLUGINS=(node exec_time git) it doesnt work though

**Comment by desyncr** [comment]
Try with `geometry_plugin_list` to check if the plugin is registered.
Example output:

```
 ▲ ~ geometry_plugin_list 
exec_time
jobs
git
node


```

Remember `node` plugin only shows when you're in a node/yarn project. See [here](https://github.com/geometry-zsh/geometry/tree/master/plugins/node).

**Comment by designMoreWeb** [comment]
<img width="257" alt="screen shot 2017-11-19 at 12 59 31 pm" src="https://user-images.githubusercontent.com/5986856/32993675-83913328-cd29-11e7-90d5-0b4ce918d7ac.png">

it says its there but it doesn't display it which is confusing

**Comment by jedahan** [comment]
exec_time has a minimum time before it displays, try something like `sleep 31 && echo 'do we see it? ->'`

**Comment by designMoreWeb** [comment]
that runs i want to see the node version which is not working

**Comment by desyncr** [comment]
Are you inside a node project? This plugin check for `package.json` or `yarn.lock` in order to display the node/npm/yarn versions.

**Comment by desyncr** [comment]
@designMoreWeb Also you could try with the following configuration:

```
GEOMETRY_PROMPT_PLUGINS=(+node exec_time git)
```

The `+` prefix makes a plugin fixed (ie, it always shows up).

**Comment by designMoreWeb** [comment]
@desyncr let me try that out hopefully it works

**Comment by designMoreWeb** [comment]
Okay the good news is i got it working now it shows up as a transparent symbol (node symbol) how do i get it to be a green filled up symbol?

**Comment by desyncr** [comment]
Take a look at the readme. There's a color configuration variable. https://github.com/geometry-zsh/geometry/blob/master/plugins/node/README.md

**Comment by designMoreWeb** [comment]
Should you put that configuration variable in the .zshrc file or it would be somewhere else? Also where do i get a filled up node symbol from the one in the readme is "⬡" which is empty


So quick update i put the GEOMETRY_COLOR_NODE_NPM_VERSION ="green" in my .zshrc file and i am getting this error when i refresh the terminal.

<img width="860" alt="screen shot 2017-11-20 at 7 55 02 pm" src="https://user-images.githubusercontent.com/5986856/33049154-bb60d91c-ce2c-11e7-8b57-12661dbc956c.png">

**Comment by designMoreWeb** [comment]
NVM i figured it all out thanks a lot :)

**Comment by desyncr** [comment]
Which configuration worked out?

**Comment by designMoreWeb** [comment]
export GEOMETRY_PROMPT_PLUGINS=(+node virtualenv exec_time git hg)
