### ISSUE TITLE
Zsh theme development processes

### ISSUE THREAD

**Issue by LuRsT** [frmendes/geometry#19]
A bit offtopic but I'm having trouble with developing for this plugin, since my process currently is just to change the repo dir inside `~/.antigen/repos/`, running antigen update and then opening a new terminal and checking if it worked. I'm using an absolute dir path in my `~/.zshrc` but antigen update doesn't seem to be tracking changes there. Do you have a better way of doing this?

**Comment by frm** [comment]
I currently use [antibody](https://github.com/getantibody/antibody) as opposed to antigen. I have the `geometry.zsh` file symlinked to the correct location of where antibody installs it. I'm actually not sure if I can provide a local path for antibody to use.

As for checking for changes, I just have `alias reload=source ~/.zshrc` and work it from there. Beware this doesn't necessarily change environment variables. In that case, I open up a new tmux tab.

If there are any other suggestions, I'd love to hear them!

**Comment by LuRsT** [comment]
I found a better way, I symlinked the `geometry.plugin.zsh` inside `~/.antigen/repos/..` but I still needed to run `antigen update` to check changes + open a new terminal, it's better but a little bit better, I'll keep looking for a better way...

**Comment by desyncr** [comment]
@LuRsT Antigen dev here, you should disable caching (with `_ANTIGEN_CACHE_ENABLED=false`) for development purposes, and as I see you already using `--no-local-clone` (by given antigen an absolute path).

**Comment by LuRsT** [comment]
@desyncr Hi! Thanks for joining in the conversation. I struggled a bit even with that config until I realized that I actually have to commit things so that they get updated when I open a new shell, is there an even easier way where I just change the script, open a new shell and check the results immediately?

**Comment by desyncr** [comment]
@LuRsT It should be unnecessary to commit things to see the changes.

This configuration show changes immediately without having to commit, reset antigen configuration or anything:

Disable antigen cache:

```
_ANTIGEN_CACHE_ENABLED=false zsh
```

Or in your `.zshrc`:

```
export _ANTIGEN_CACHE_ENABLED=false
```

Then I have the following antigen configuration:

```
antigen bundle $HOME/Playground/dev-bundle bundle.zsh
antigen apply
```

You should be good to go.

Hope that helps!

**Comment by LuRsT** [comment]
Hi @desyncr, that was exactly what I was trying yesterday to no avail.

I added the `export _ANTIGEN_CACHE_ENABLED=false` to the top of my `~/.zshrc`, replaced my `antigen bundle` with the absolute path of my repo dir, and after editing the file in my repo, nothing happens.

With this setup, what I have to do to check changes is:
- Change file in repo
- `git commit` my changes
- `rm -rf ~/.antigen/repos/-SLASH-....`
- Open new terminal

Am I missing something? I even tried removing the symlink that this repo uses thinking that it could help, but nope. For now, I'll stick to:
- Change file in `~/.antigen/repos/-SLASH.../plugin.zsh`
- Open new terminal to check changes
- Copy file over to my repo

Thanks for your help!

**Comment by LuRsT** [comment]
@desyncr OK, after thinking about this a while, I checked the code in `antigen.zsh` and it appears that the CACHING var doesn't do what I want since the file inside `~/.antigen/repo...` is not being updated everytime after I open a new terminal, which is what I want, so antigen is still reading the file stored there rather than the cache, but the file is still the old version. What I actually need to do what I want is someway of making antigen pull everything, everytime I open a new terminal (optionally for absolute paths, not caring whether it's a git repo or not)

UPDATE: OK, I got something better now:
- `ln` my file from my repo into `~/.antigen/repo/-SLASH...`
- Disable caching
- :sparkles:

This does what I want, edit file, open new terminal :boom: new stuff in new terminal!

**Comment by LuRsT** [comment]
OK, last update, I finally figured it out, I was missing the `--no-local-clone` option that you referenced in your first comment, that is what makes it not use the `~/.antigen/repo` folder. Thanks for the help :heart: !

**Comment by desyncr** [comment]
@LuRsT Glad you got it working :+1:.

Passing a full path should be the same as using `--no-local-clone`. I'll take a look to see what's going on.
