### ISSUE TITLE
Create sub-theming examples

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#195]
This should be put up in a repo under geometry-zsh org. The idea is to have a customization-show off section for the upcoming release.

Also see this Trello card https://trello.com/c/RFZ7wUbW/19-subtheming-add-a-section-on-the-readme-mentioning-it

**Comment by jedahan** [comment]
How about we start with a call for help from the community? 

For example https://github.com/geometry-zsh/geometry/wiki/prompts

Pinging for help from anyone who ever participated in the community - if you are using geometry we'd love to see your customizations. Especially if its really different from the defaults. Thanks!

@pbar1 @chrisjlee @snbsniper @f-a-a @tp00012x @kreedz @terry182 @agusdmb @glennraganas @mustaqimM  @vinhpz @ev-agelos  @boldhaus @wyudong @cnguy @keelan542 @FildasPA @castellanprime @LuRsT @SephVelut @wuvs @shridharmanvi @zetaron

**Comment by LuRsT** [comment]
Good idea, although instead of customizing my prompt, I only have two settings set to true (PROMPT_VIRTUALENV_ENABLED and PROMPT_GEOMETRY_GIT_CONFLICTS) and I have my own fork where I removed a few things I didn't use.

**Comment by jedahan** [comment]
Seeing as this is a year old, even though its a good idea I think we can close it. Maybe reopen during next years hacktoberfest or something.
