### ISSUE TITLE
Bug: "geometry_prompt:1: command not found: add-zsh-hook"

### ISSUE THREAD

**Issue by plul** [frmendes/geometry#2]
I get the following error when trying to use geometry:

```
geometry_prompt:1: command not found: add-zsh-hook
geometry_prompt:2: command not found: add-zsh-hook
```

Any way to fix that?

**Comment by frm** [comment]
Hi @plul ! I just pushed a fix for this. Can you confirm if it now works for you?

**Comment by plul** [comment]
Yes it works now! Thank you!
