### ISSUE TITLE
IntelliJ terminal glitches geometry theme.

### ISSUE THREAD

**Issue by lucassith** [frmendes/geometry#202]
I wasn't sure if it is even an issue with the theme itself but I need to do some understanding before I open the ticket on IntelliJ site. So basically the problem is that when there are too many icons on the right side of the terminal (git info) then the IDE's terminal will render new line. 
![image](https://user-images.githubusercontent.com/7236601/36412461-b3c6d108-161a-11e8-8988-07f237ed0afb.png)

There is also another glitch where if I start typing too fast before the git data renders then the first character is kind of "out of index" 
![image](https://user-images.githubusercontent.com/7236601/36412675-80de1034-161b-11e8-9efd-d0ba4b0d3ca2.png)

Just let me know if this is a known issue or there is any fix via config. If not then I will contact IntelliJ's support. Thanks.

**Comment by frm** [comment]
Does this happen with other themes that have a right side prompt?

**Comment by lucassith** [comment]
Yes it does happen with other themes. I have opened a ticket on IntelliJ product and it seems that they are aware of this bug. https://youtrack.jetbrains.com/issue/IDEA-184513
