### ISSUE TITLE
Going to next line bug

### ISSUE THREAD

**Issue by tp00012x** [frmendes/geometry#207]
For some reason, I'm having this issue where the word 'producthunt' which is my conda enrionment's name is going to the next line. 

<img width="1264" alt="screen shot 2018-03-20 at 5 45 47 pm" src="https://user-images.githubusercontent.com/24213795/37686737-ae971b86-2c66-11e8-9b6f-b67dd32282ba.png">

**Comment by frm** [comment]
Can you post your configs?

**Comment by jedahan** [comment]
I cannot reproduce this issue on v2. Feel free to open if its still a problem.
