### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by designMoreWeb** [frmendes/geometry#208]
Hey This is not an issue but I really liked the color scheme you guys had on the repo. Could you tell me how you made that and if you could share the settings for it that would be great.

**Comment by jedahan** [comment]
The first gif shows uses [new moon](https://github.com/taniarascia/new-moon/), not sure what themes @desyncr and @fribmendes use

**Comment by designMoreWeb** [comment]
@jedahan how do you apply that theme to the geometry theme/terminal?

**Comment by frm** [comment]
Most of the older screenshots I put in the repo were using [base-16](https://github.com/chriskempson/base16-shell), although I have been using a variation of [hybrid](https://github.com/w0ng/vim-hybrid) for iTerm.

**Comment by jedahan** [comment]
I manually set the colors in [alacritty](https://github.com/jwilm/alacritty/) in my [alacritty config](https://github.com/jedahan/dotfiles/blob/master/.config/alacritty/alacritty.yml#L84-L108).

**Comment by designMoreWeb** [comment]
@jedahan what is alacritty?
Never heard of it 
I have been using [https://hyper.is/](url) as my terminal for a good 3 years now

**Comment by jedahan** [comment]
Its the terminal I linked - its a minimal terminal written in rust that uses the gpu to draw. I played around with hyper.is, which is nice too.

**Comment by designMoreWeb** [comment]
is there any benefit of alacritty over traditional terminals? does it offer something more like what tmux and a few other terminal programs offer?

**Comment by jedahan** [comment]
Technically, the main reason I use it is because its faster. Socially, I like the decision making and active development. Sounds silly "my terminal is plenty fast" but I noticed it. If you want to play around with a new terminal try it out. If you are looking for a replacement for hyper, well it ain't close to as full featured, at least not until the scrollback branch is released.

**Comment by frm** [comment]
I switched to alacritty last month or so. I've been very happy ever since. Scrolling on nvim + tmux was shaky in iTerm, but amazing in alacritty.
