### ISSUE TITLE
Possibility of a Fish Shell port

### ISSUE THREAD

**Issue by mustaqimM** [frmendes/geometry#209]

**Comment by frm** [comment]
I'd be up for that, I've been considering switching to fish for a while now. What are your thoughts @desyncr @jedahan ?

**Comment by jedahan** [comment]
I used fish a couple of years ago. Our codebase isn't that big, but a big part of it being nice are the plugins. I'd be up for seeing a fish shell port but wonder if there's a good way to have plugins not need to be completely rewritten

**Comment by jedahan** [comment]
Or rather to write plugins that work with both

**Comment by jedahan** [comment]
Closing and if someone makes a fish port, would be interested in seeing how it compares.
