### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by chrisl8888** [frmendes/geometry#211]
Don't see a license file. Is it MIT? 

If so i can provide a PR.

**Comment by frm** [comment]
Good point. I'd rather have it be MIT. @jedahan @desyncr any thoughts?

**Comment by jedahan** [comment]
I like ISC, which is a simplified MIT, but am fine with whatever

**Comment by frm** [comment]
I'm fine with ISC. @chrisjlee do you want to do a PR? 🙂

**Comment by chrisl8888** [comment]
Sure who's name or entity should i provide? And did you decide on ISC or MIT?

**Comment by jedahan** [comment]
I'd say @fribmendes , ISC

**Comment by chrisl8888** [comment]
Sweet thanks!
