### ISSUE TITLE
Error: Could not load zsh-async library.

### ISSUE THREAD

**Issue by GlennRaganas** [frmendes/geometry#213]
Followed installation instruction but i keep getting this error after "source ~/.zshrc"
I'm not sure i did anything wrong? Any tips?

**Comment by GlennRaganas** [comment]
Nevermind! cloning the repo into custom/themes rather than dragging and dropping seemed to have fixed the issue.

**Comment by vyorkin** [comment]
Seems like I have the same error:
```
fatal: not a git repository (or any of the parent directories): .git
Error: Could not load zsh-async library
```
