### ISSUE TITLE
Use geometry plugin without changing theme

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [frmendes/geometry#218]
This might sound like a noob question, but I am interested in using a geometry plugin (the [hydrate plugin](https://github.com/jedahan/geometry-hydrate) more specifically), but I want to keep my current oh-my-zsh theme.

Is there any way of installing geometry and the plugin, while maintaining my theme?

**Comment by jedahan** [comment]
Right now there is a lot of integration between the plugins and geometry, so possible options include:

1. Recreating the theme you are using within geometry

Geometry is really really customizeable, it may be easiest to look at the features of your current theme and just see if it can be recreated easily within geometry.

2. Port geometry hydrate to your current theme

The code is pretty small https://github.com/jedahan/geometry-hydrate/blob/master/plugin.zsh so it should be pretty easy to port.

The most basic parts are:
```zsh
# settings
GEOMETRY_PLUGIN_HYDRATE_FILE=${GEOMETRY_PLUGIN_HYDRATE_FILE:-${TMPDIR:-/tmp}/water}
GEOMETRY_PLUGIN_HYDRATE_INTERVAL=${GEOMETRY_PLUGIN_HYDRATE_INTERVAL:-30} # in minutes

# check if we should hydrate
test $(print $GEOMETRY_PLUGIN_HYDRATE_FILE(.Nmm+$GEOMETRY_PLUGIN_HYDRATE_INTERVAL))  && echo "time for water! (render icon however you are supposed to in your theme)"

# provide a hydrate function
hydrate() { touch $GEOMETRY_PLUGIN_HYDRATE_FILE }
```

**Comment by BrunoGomesCoelho** [comment]
I see, thanks for the quick answer!

I'll give recreating the theme a try, if it doesn't really give something me similar I'll probably port it on my holidays; it will give me a chance to learn shell at least :D

If I do port I'll be sure to send a message on the hydrate plugin and here if anyone else comes across this.
