### ISSUE TITLE
Plugin ordering?

### ISSUE THREAD

**Issue by pbar1** [frmendes/geometry#220]
Is it possible to order plugins? I made the custom plugin [geometry-terraform](https://github.com/pbar1/geometry-terraform) to display the Terraform workspace of the current directory, and while it does work, the plugin placement is off:

![image](https://user-images.githubusercontent.com/26949935/43237850-42642d9c-9051-11e8-999a-b427b1f46424.png)

This is the configuration I'm using in my zshrc, and I'd assume terraform would come first:
```
▲ ~ cat .zshrc | rg GEOMETRY
export GEOMETRY_PROMPT_PLUGINS=(terraform exec_time jobs node virtualenv kube git)
```

Versus this, the output I get from `geometry_plugin_list`; terraform is now at the end of the list, while the order of the rest of the plugins is still intact:
```
▲ ~ geometry_plugin_list
primary:
path hostname
secondary:
exec_time jobs node virtualenv kube git terraform
```

What can I do to ensure the ordering is correct?

(This theme is incredible btw! It makes my daily dev work smoother and more fun)

**Comment by jedahan** [comment]
Interesting issue. Just for giggles, can you try using GEOMETRY_PROMPT_PLUGINS_SECONDARY instead of GEOMETRY_PROMPT_PLUGINS and see if that fixes it?

**Comment by pbar1** [comment]
Changing to GEOMETRY_PROMPT_PLUGINS_SECONDARY has the same effect. Looking at the [code](https://github.com/geometry-zsh/geometry/blob/181839d1a5a5b3576977a65fbfb57219cc40ad4f/lib/plugin.zsh#L37) it looks like it might be because default plugins are registered all at once, and then third party ones are registered afterward?

**Comment by jedahan** [comment]
Looks like thats the issue. Unfortunately I won't have time to look at it for a few weeks. If anyone else wants to try and fix it I can do a code review though.

Otherwise feel free to ping in a couple of weeks

**Comment by jedahan** [comment]
If we merge #233 we will be able to close this

**Comment by jedahan** [comment]
fixed by v2
