### ISSUE TITLE
Error configuring plugins: bad set of key/value pairs for associative array

### ISSUE THREAD

**Issue by lox** [frmendes/geometry#221]
Apologies if this is a zsh issue, or something with my configuration, but I'm not able to set the plugin configuration as documented:

```
 ▲ ~ export GEOMETRY_PROMPT_PLUGINS=(terraform exec_time jobs node virtualenv kube git)
zsh: bad set of key/value pairs for associative array

 ✗ ~ zsh --version
zsh 5.5.1 (x86_64-apple-darwin17.5.0)
```
Any ideas? I assume the error is because $GEOMETRY_PROMPT_PLUGINS is already defined as an associative array somewhere?

**Comment by jedahan** [comment]
I think we only support setting loaded plugin list before sourcing zsh.

If you need to load interactively you might need ` typeset -a` or `typeset -gA` first, or look at PROMPT_GEOMETRY_PLUGINS_PRIMARY which is an indexed array.

Sorry I can be of more help for a while

**Comment by WhiteAbeLincoln** [comment]
I'm getting the same issue when setting GEOMETRY_PROMPT_PLUGINS in my zshrc file

**Comment by jedahan** [comment]
@WhiteAbeLincoln can you share your zshrc? As long as the variable is exported before sourcing geometry.zsh I'd hope that it works.

**Comment by WhiteAbeLincoln** [comment]
It looks like that was the issue. I had exported the variables only after geometry was sourced, and hadn’t noticed before because the default behavior was what I needed until now.
