### ISSUE TITLE
wishlist: support 'external' zsh-async rather than forcing internal version

### ISSUE THREAD

**Issue by slippycheeze** [frmendes/geometry#222]
It would be nice to support an externally installed version of zsh-async in this code.  For example, testing if the functions were present in the shell before sourcing the internally shipped version would help avoid overwriting a newer version with an older embedded version.

This isn't strictly necessary since loading async after this code would give the appropriate result, redefining things again, but ... sure would be nice to be smarter. :)

**Comment by frm** [comment]
I wouldn't oppose this, we're blindly sourcing `zsh-async` and that might already be loaded.

Looking at https://github.com/mafredri/zsh-async/blob/master/async.zsh I believe we can test for the existence of the `ASYNC_VERSION` variable (which is only available in the most recent versions). To avoid forcing users to update, we could also test the `async` function

**Comment by jedahan** [comment]
I think `async_init` already does this for us

https://github.com/mafredri/zsh-async/blob/master/async.zsh#L525-L527

```zsh
async_init() {
    (( ASYNC_INIT_DONE )) && return
    typeset -g ASYNC_INIT_DONE=1
```

**Comment by jedahan** [comment]
so our embedded version would not load if you already loaded zsh-async

**Comment by jedahan** [comment]
If the behaviour changes, feel free to reopen, but I think this is a non-issue since zsh-async gracefully handles this for us
