### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by drager** [frmendes/geometry#228]
Hey, thank you for great prompt!

I have made some plugins and I just wonder if I should add PR's for them to geometry or simply provide links to them instead?

Let me know what you think, thanks.

**Comment by jedahan** [comment]
The easy thing to do is add them to the wiki first https://github.com/geometry-zsh/geometry/wiki/plugins , but I am open to PRs as well.

**Comment by drager** [comment]
Alright, I'll add them to the wiki first and then we can see if there are any you want to have in the repo instead. :blush:

**Comment by drager** [comment]
I have added them to the wiki page: https://github.com/geometry-zsh/geometry/wiki/Plugins#npm-package-version

**Comment by jedahan** [comment]
These look great! I'm going to hold off on adding them to the repo until #229 is resolved :)

**Comment by jedahan** [comment]
I ported these to my branch of geometry in https://github.com/jedahan/geometry/commit/51ebb5eda2dd544d865921aa4658637f0baa61b5. When that gets released, your contributions will be available for everyone in geometry :)

**Comment by drager** [comment]
@jedahan Awesome! :tada:

**Comment by jedahan** [comment]
They are in v2!
