### ISSUE TITLE
Option to disable RPROMPT

### ISSUE THREAD

**Issue by z0rc** [frmendes/geometry#23]
Having RPROMPT when running a subshell in midnight commander produces all kind of weirdness. I used to disable it completely under such condition. All I need is an option in geometry to do so. Probably I can hack it around without changing the geometry, but messing with precmd hooks isn't a sane way to maintain it.

**Comment by frm** [comment]
So, you're saying you want to disable `RPROMPT` at all or just mitigate the effects of running commands in a subshell?

**Comment by z0rc** [comment]
The RPROMPT itself, potentially this means skipping git info virtualenv info calls for saving cycles. Basically `mc` messes with it that much that is stops being the _right_ prompt.
![screen shot 2016-10-21 at 14 53 11](https://cloud.githubusercontent.com/assets/787519/19597588/24c8c124-979e-11e6-92e9-73237fcb6e15.png)

**Comment by desyncr** [comment]
Probably just branch off the [following lines](https://github.com/frmendes/geometry/blob/master/geometry.zsh#L262).

**Comment by desyncr** [comment]
Unless anybody else wants to take up this task I'm gonna start it.
