### ISSUE TITLE
Magic enter function?

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#234]
mnml supports a magic enter function, which might be really cool to implement, what do we think?

**Comment by frm** [comment]
Do you mean a function that is autorun when you `cd`?

**Comment by jedahan** [comment]
A function that is run when you hit enter with no command.

**Comment by jedahan** [comment]
Beta version of this is present on https://github.com/geometry-zsh/geometry/tree/info-command

It adds `GEOMETRY_INFO=(geometry_hostname geometry_jobs)` and runs those commands on enter if the buffer is empty.

**Comment by jedahan** [comment]
added to https://github.com/jedahan/mnml
