### ISSUE TITLE
remove geometry_ prefix for built-in plugins?

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#235]
I would like to remove the geometry_ prefix for built-in plugins, but maybe thats a waste and will just cause conflicts?

**Comment by frm** [comment]
I think we should keep it to avoid conflicts but it's really long. We can change to something like `_gmtr_*`, what do you think?

**Comment by jedahan** [comment]
i'd rather have it be the same name as the theme, even if it is verbose people will know what it is on first read

**Comment by jedahan** [comment]
hey :: is allowed in function names, I started using `geometry::` to prefix things, it seems nicer.
