### ISSUE TITLE
Option to add custom prefix/postfix to PROMPT

### ISSUE THREAD

**Issue by z0rc** [frmendes/geometry#24]
I'd like to define my own indicators that will be included in PROMPT. I can easily create a function or variable to return indicator string, but I miss is a proper way to inject it into geometry PROMPT.

**Comment by frm** [comment]
You can change the prompt symbols, if I understood correctly.

Simply export one of [these variables](https://github.com/frmendes/geometry/blob/master/geometry.zsh#L27-L37) in your `.zshrc`.

You can find an example [in my dotfiles](https://github.com/frmendes/dotfiles/blob/master/system/prompt.zsh#L18-L24). I'm changing the exit value symbol plus a couple of colors.

**Comment by z0rc** [comment]
Not really what I need. I want to expand prompt with my own data. Technically this looks doable with adding my strings to symbols there. But I'd like to see something like https://github.com/nojhan/liquidprompt#adding-a-prefixpostfix

**Comment by desyncr** [comment]
Maybe some kind of callback, ie `geometry_(r)prompt_[pre|post]_callback` but I think it's too complex to implement to be fully customizable.

**Comment by frm** [comment]
It seems a bit complex, yeah. I think I'll let this hang on the bottom of the list since there are more pressing issues and features.

**Comment by desyncr** [comment]
@z0rc Now geometry has support for plugins (#43, #45 ), which means you can add your custom prompts into geometry. [Here](https://github.com/desyncr/geometry-dir-info-prompt) is a working example.

**Comment by desyncr** [comment]
I'm closing this as it should be solved.
