### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#240]
Is it safe to delete [some of the branches](https://github.com/geometry-zsh/geometry/branches)?

These look safe to delete:
- https://github.com/geometry-zsh/geometry/tree/feature/vi-mode-plugin
- https://github.com/geometry-zsh/geometry/tree/bugfix/support-5.0.0

Not sure about the others

**Comment by jedahan** [comment]
ping @desyncr can we delete those two branches?
And @justmendes is the issue that https://github.com/geometry-zsh/geometry/tree/frm/prompt-utf8 fixes present in the mnml branch? https://github.com/jedahan/geometry ?

**Comment by frm** [comment]
I'd support deleting them if there are no recent changes. That was an attempt at fixing the UTF-8 issue, but it was more complex than I anticipated. I prefer if we let it go and try again from your rebase.

**Comment by jedahan** [comment]
cleaned up. vi-mode-plugin will need to be rewritten unfortunately
