### ISSUE TITLE
The geometry theme incorrectly installed

### ISSUE THREAD

**Issue by dyrkow** [frmendes/geometry#243]
Hi, I use the following manual:

Clone this repository as follows:
```
git clone https://github.com/geometry-zsh/geometry
cd geometry
git submodule update --init --recursive
```
Then add it to your .zshrc configuration:
```
source /path/to/geometry/geometry.zsh
```

And in result I have

![image](https://user-images.githubusercontent.com/8726541/49751605-d86fee00-fcbe-11e8-981e-3ef7099c9a38.png)

Not this

![image](https://user-images.githubusercontent.com/8726541/49751643-f50c2600-fcbe-11e8-8119-598013ebda39.png)

What I can do with it?

**Comment by jedahan** [comment]
By default, we show the path and hostname. If you just want the path, you can add `export GEOMETRY_PROMPT_PLUGINS_PRIMARY=(path)` before `source geometry.zsh`. This will only show the triangle and directory.

The `[` and `]` brackets at the beginning and end seem to be something with Terminal.app that I am not sure what it is.

So the only thing that looks out of place is is the `::` on the left hand side - can you share your entire `~/.zshrc` file?
