### ISSUE TITLE
Sample configuration as seen in the gif

### ISSUE THREAD

**Issue by mmathys** [frmendes/geometry#244]
I am curious about the configuration used in the gif:

- what is the name of the autocomplete module used?
- how can I configure zsh so that the command gets a separate color, while the rest of the command gets another?

**Comment by jedahan** [comment]
My dotfiles are up on https://github.com/jedahan/dotfiles/, [zshrc](https://github.com/jedahan/dotfiles/blob/master/.zshrc#L37-L53)
* [autocomplete](https://github.com/zsh-users/zsh-autosuggestions)
* [syntax highlighting](https://github.com/zdharma/fast-syntax-highlighting)

**Comment by mmathys** [comment]
Thank you!
