### ISSUE TITLE
test refactoring geometry_git to use vcs_info

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#245]
vcs_info might be faster, might be slower.

How can we benchmark it?

Even if its 20% slower, does it help reduce complexity?

**Comment by frm** [comment]
> How can we benchmark it?

Define a set of large and smaller repos and maybe use zprof?

> Even if its 20% slower, does it help reduce complexity?

This is a tradeoff I'm willing to have if it's maintainable for us and usable at the same time. It might not even be fast by default but configurable to be fast - e.g. the user disables certain features if they want speed.

**Comment by jedahan** [comment]
https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples

http://zsh.sourceforge.net/Doc/Release/User-Contributions.html
