### ISSUE TITLE
prompt_geometry_render:local:13: not valid in this context: %F{242}master%f

### ISSUE THREAD

**Issue by nmbarker** [frmendes/geometry#25]
Alright, so i'm running the latest version of oh-my-zsh and I've gone through the tutorial on your page and keep getting the same error for the theme "geometry":

`prompt_geometry_render:local:13: not valid in this context: %F{242}master%f`

but the triangle will still load...
Any thoughts?

**Comment by frm** [comment]
What OS and which version are you running? Also, what's the zsh version?

**Comment by nmbarker** [comment]
Running 
Mac OSX El Capitan 10.11.4
ZSH --version > 5.0.8

**Comment by nmbarker** [comment]
I've got a new error launching in iTerm vs Hyper term:

Hyper term returns the one above, however iTerm returns:
`prompt_geometry_render:15: unknown file attribute:`

**Comment by nmbarker** [comment]
Edit:
I went through and looked at the code, Hyperterm no longer returns:
`prompt_geometry_render:local:13: not valid in this context: %F{242}master%f`
But now returns the same as iTerm2:
`prompt_geometry_render:15: unknown file attribute:`

**Comment by jchris** [comment]
I'm seeing this on Terminal on a stock zsh 5.0.8 and El Capitan 10.11.6

**Comment by nmbarker** [comment]
@jchris So what would your solution be, if you have one?

**Comment by terry182** [comment]
@jchris @n-m-b I happen to encounter this problem but temporarily solving this problem when I call `zsh` in `zsh` again. 

Update:
This problem will be solved if you have `zsh` 5.2 installed by home-brew. But I still can't Figure out why this will work

**Comment by nmbarker** [comment]
Alright so the only fix i've found is by installing ZSH version 5.2 by homebrew. Otherwise I don't see a fix any time soon.

**Comment by desyncr** [comment]
So this only happens on `5.0.x`? I'll try to check geometry on `5.0.8` later tonight.

**Comment by nmbarker** [comment]
@desyncr I used to have 5.0.8 and have no idea of how I installed it. I think I did it through a binary, all I know is that the brew install fix everything for me and I've got powerline symbols and no errors.
