### ISSUE TITLE
Investigate non-pty async for rprompt

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#254]
From http://www.zsh.org/mla/users/2018/msg00424.html and https://github.com/mafredri/zsh-async/issues/24

**Comment by jedahan** [comment]
test version https://github.com/jedahan/geometry/pull/new/simple-async

has some weirdness & possible slowdowns, but really nice to not need zsh-async

**Comment by scottstanfield** [comment]
I'm taking it for a spin now.

**Comment by jedahan** [comment]
cool, did it work?

**Comment by scottstanfield** [comment]
Yes, with the exception of one weird issue. Hitting <enter> at the prompt, without typing anything, echo's my login name and machine name, then gives me a new prompt. 

Recording: https://asciinema.org/a/bHqGPntVSKrR7HjFqNZKoEfdA

**Comment by scottstanfield** [comment]
If I set `GEOMETRY_INFO=(geometry_jobs)` the `geometry_hostname` goes away on an empty line. So not an issue with your changes. So far so good!
