### ISSUE TITLE
LS colors aren't showing correctly

### ISSUE THREAD

**Issue by CarlosMed** [frmendes/geometry#256]
So when doing `ls + space + tab` for completions the colors seem to be that green color making it pretty much unreadable.

Meanwhile doing just a `ls + enter` the colors become that beige/yellow color. Was wondering if theres a fix? If it might be Oh-My-ZSH or the Geometry theme.

<img width="267" alt="Screen Shot 2019-04-03 at 11 37 12 PM" src="https://user-images.githubusercontent.com/7547059/55528688-be8e5880-566b-11e9-9c60-7892588ff037.png">

I am using iTerm2 as my terminal of choice with Atom color preset.

**Comment by jedahan** [comment]
That is definitely a iterm2 or oh-my-zsh issue. oh-my-zsh ships with a not great version of some zsh autocomplete plugin usually.
Can you reproduce this with a minimal zshrc, something like
```
# ~/.zshrc-issue-256-carlosmed
source /path/to/geometry-zsh/geometry/geometry.plugin.zsh
fpath+=/path/to/geometry-zsh/geometry/
PATH=/path/to/geometry-zsh/geometry:$PATH
```
and run with
```
zsh --no-rcs --no-globalrcs --login -c "~/.zshrc-issue-256-carlosmed"
```

also congrats on nabbing issue `0x100` :)

**Comment by CarlosMed** [comment]
So I actually figured out the reason why. It has to do with setting the permissions set on folders and file. If you give it a `chmod 777 <folder>` you get the ugly colors. but if you set it to `chmod 755 <folder>` you'll have the correct coloration.

From my research it seems that the way Mac sets `LS` colors is not so well which cause the weird colors. I am going to check the above that you posted though and see if it achieves anything but as far as a fix its the above.
