### ISSUE TITLE
Up arrow not displayed in README screencast gif

### ISSUE THREAD

**Issue by wolf99** [frmendes/geometry#258]
https://github.com/geometry-zsh/geometry/blob/master/screenshots/screencast.gif

I think I got  headache trying to see the non-existent up arrow.

**Comment by jedahan** [comment]
I would love for someone to record a new screencast, especially using https://github.com/nbedos/termtosvg

**Comment by jedahan** [comment]
Very sorry for the confusion TT

**Comment by jedahan** [comment]
I recorded a new [screencast](https://raw.githubusercontent.com/geometry-zsh/geometry/mnml/images/screencasts/git.svg)
