### ISSUE TITLE
`read -r line` doesn't work

### ISSUE THREAD

**Issue by psprint** [frmendes/geometry#262]
Hello,
with the prompt loaded:
```zsh
% read -r line
abcdef
% print -rl "$line" ""
<no output>
```

With different variable name:

```zsh
% read -r line2
abcdef
% print -rl "$line2" ""
abcdef

```

I'd suggest the use of `setopt localoptions warncreateglobal` to avoid such problems in future.

**Comment by jedahan** [comment]
@psprint if we `setopt localoptions warncreateglobal` will they be unset after sourcing the prompt? Or do we also have to see if they were set before and restore to original state?

**Comment by jedahan** [comment]
I started to maintain my own fork of geometry, called `mnml`. This should be fixed in https://github.com/jedahan/mnml/commit/051c7d50f237b612e72cf188444a0a535386bdf8

**Comment by psprint** [comment]
@jedahan: Your own fork? I do not understand :) You're the author of this great prompt, aren't you? So what does it mean to maintain an "own" fork?

The setopt should go into preamble of any function, basically. The option will be *local*, i.e. reverted if needed automatically after exit from function.

**Comment by jedahan** [comment]
Ahh thanks for helping me understand setoptions in function context.

The original author is @justmendes , and @desyncr . I joined later, and rewrote a decent amount of it, but do not have admin rights to this repository, so I cannot do things like change the default branch.

My release strategy was to change the default branch, then add a deprecation warning to the master branch, but maybe there is another option. I think everyone else got busy with life, and I got impatient.

**Comment by psprint** [comment]
Ahso, thanks for introducing me to the history of the project. I might switch to your fork, I'll test it and see.

PS. Github doesn't count contributions done to forks. AFAIR, you can contact GH with request to not treat the mnml repository as a fork.

**Comment by jedahan** [comment]
Got admin for geometry! We are back in mainline! Thanks for your patience @psprint, feel free to migrate back (one last time) to the regular geometry.

**Comment by psprint** [comment]
Congratulations :) Ok, I'll migrate back :)
