### ISSUE TITLE
Change default geometry_git_separator from " :: " to " "?

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#277]
This would be a minor breaking change, but inspired by https://github.com/diogoazevedos/hexagon/commit/904e0b5ffd11ba72fbb270de9d41b8f5632fe182 , its weird that geometry_git is the only plugin that treats its output differently.

We might even be able to remove GEOMETRY_GIT_SEPARATOR completely.

How do we feel about this?

**Comment by alxbl** [comment]
Using the global separator makes sense. My guess for the initial use of `::` is probably because the branch is technically part of the git widget and is thus logically a single unit in the prompt. In any case, the output would be less cluttered. 

I don't have a preference on this.

**Comment by jedahan** [comment]
I think this also fits in better with the fact that a complicated function like `geometry_git` is just made up of 5 smaller functions. Easier to learn from. I am open to reverting this change before the next tagged release.
