### ISSUE TITLE
command not found: geometry_plugin_register when installing plugins both manually and with antigen

### ISSUE THREAD

**Issue by sornas** [frmendes/geometry#281]
I installed geometry with `git clone --recursive https://github.com/geometry-zsh/geometry $HOME/git/zsh-geometry` and my .zshrc looks like this.

```
source /usr/local/share/antigen/antigen.zsh

source $HOME/git/zsh-geometry/geometry.zsh
export GEOMETRY_STATUS_SYMBOL="$"
export GEOMETRY_STATUS_SYMBOL_ERROR="$"

antigen use oh-my-zsh

antigen bundle git
antigen bundle taskwarrior

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle desyncr/geometry-dir-info-prompt

antigen apply

source $HOME/git/zsh-geometry-host-info/host_info.zsh
```

When I start my shell I get

```
/Users/gustav/.antigen/bundles/desyncr/geometry-dir-info-prompt/plugin.zsh:14: command not found: geometry_plugin_register
/Users/gustav/git/zsh-geometry-host-info/host_info.zsh:16: command not found: geometry_plugin_register
```

Additional information:
```
$ zsh --version
zsh 5.7.1 (x86_64-apple-darwin18.2.0)
$ antigen help
Antigen v2.2.3 (ff391b5)
Revision date: 2018-01-02 13:19:57 +0100
# ...
```

**Comment by alxbl** [comment]
Hi @sornas,

Are you on the `mnml` branch? The host_info plugin was made for Geometry V1 (`master` branch) and is not compatible with V2. Converting it should not be too difficult, but it will not work as-is.

Also, I'm not too familiar with antigen, but geometry being an oh-my-zsh theme, I'm not sure if you can just source it directly like that, it would probably need to be configured as your OMZ theme by setting `ZSH_THEME=geometry` before OMZ gets sourced by antigen. I may be wrong on this.

**Comment by sornas** [comment]
You are correct that I am on `mnml`, it works correctly on the `master`-branch. Thanks! Do you know where I can find out more about how plugins work in v2? I can't seem to find any plugins for v2 to look at, and the wiki only mentions [this, apparently outdated guide](https://github.com/geometry-zsh/geometry/blob/master/plugins/README.md). I'd rather not stay on v1.

Sourcing it directly apparently works fine without me setting `ZSH_THEME`.

**Comment by sornas** [comment]
Wait, I can look at the built-in plugins.

**Comment by sornas** [comment]
Thanks for the help!

**Comment by jedahan** [comment]
If there are any functions you find useful please share them!
