### ISSUE TITLE
Explicit args for default plugins

### ISSUE THREAD

**Issue by kyeshmz** [frmendes/geometry#282]
Hey,
I have been following this guide to add my plugins to my config under zsh like so
`GEOMETRY_PROMPT_PLUGINS=(virtualenv git hg node)`
but I still see exec_time, is it possible to explicitly call this plugin off? 
If there is a possibility, I would gladly update the docs

https://github.com/geometry-zsh/geometry/tree/master/plugins

**Comment by jedahan** [comment]
Can you try using [our default branch (mnml)](https://github.com/geometry-zsh/geometry/tree/master/plugins)? Should be configurable that way.

**Comment by kyeshmz** [comment]
Worked great!  On zplug it was just 
zplug "geometry-zsh/geometry", from:github, at:mnml with the geometry stuff somewhere else. 
I think this could be more explicit on the docs, perhaps the geometry page on master?

**Comment by jedahan** [comment]
Glad it works how you'd like it to! So `mnml` is the default branch when you git clone geometry-zsh/geometry. I'd imagine zplug should respect default branches if they are not `master`. Alternatively we can rename `mnml` to `master` but I'd rather change it to `main` or `stable` tbh, which would still have the same issue.
