### ISSUE TITLE
clobber ASYNC_FD

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#286]
From https://lobste.rs/s/cqfvct/zsh_prompt_with_asynchronous_git_status#c_bkf2od
```
geometry::rprompt:2: can't clobber parameter GEOMETRY_ASYNC_FD containing file descriptor 11
```
Secondly, I noticed with the slowhi example here that the whole RPROMPT only updates after 7 seconds. Somehow I thought async function updates completing independently would make RPROMPT update with them.

**Comment by j16sdiz** [comment]
Got the same "only update after 7 seconds" problem here.

If I hold the `ENTER` key in git repository, it give `zsh: error on TTY read: Input/output error` and crash.

OS X, zsh version 5.7.1

**Comment by jedahan** [comment]
Duplicate of #289
