### ISSUE TITLE
geometry::wrap prints unneeded space if output of called function is empty or single-space

### ISSUE THREAD

**Issue by Konsonanz** [frmendes/geometry#291]
**Describe the bug**
If one of the functions passed to the `geometry::wrap`-method returns empty or space, the output from the method will also include an unneeded space.

**To Reproduce**
![1](https://user-images.githubusercontent.com/46794176/72250178-e3e4c580-35f2-11ea-9b22-125d26723cb6.png)
Notice the 3 spaces after the output from `geometry_path`, and the 2 spaces after `geometry_git_branches`, resulting in an overall uneven prompt.

**Expected behavior**
`geometry::wrap` should ignore empty or space-output from called functions. If applying the following patch, then the behaviour returns to the expected:
```diff
diff --git a/geometry.zsh b/geometry.zsh
index c89b9d3..56af673 100644
--- a/geometry.zsh
+++ b/geometry.zsh
@@ -73,7 +73,7 @@ geometry::wrap() {
   local -a outputs
   local cmd output
   shift
-  for cmd in $@; do output=$($cmd); (( $? )) || outputs+=$output; done
+  for cmd in $@; do output=$($cmd); ( (( $? )) || [[ -z "${output// }" ]] ) || outputs+=$output; done
 
   echo "${(ej.${GEOMETRY_SEPARATOR:- }.)outputs}"
 }
@@ -95,7 +95,7 @@ geometry::rprompt() {
 
 geometry::prompt() {
   GEOMETRY[LAST_STATUS]="$status"
-  PROMPT="$(geometry::wrap $PWD $GEOMETRY_PROMPT) "
+  PROMPT=" $(geometry::wrap $PWD $GEOMETRY_PROMPT) "
   geometry::rprompt
 }
 
```
This result in even spacing:
![2](https://user-images.githubusercontent.com/46794176/72250684-10e5a800-35f4-11ea-9558-f5bab89c2690.png)

**Comment by jedahan** [comment]
Thanks for the fixes! About to apply them and release a new version, but I wonder if they are bandaids revealing some larger problems:

1) do we hide errors with the eval? should we print them to stderr?

2) what functions are creating an empty output? should they be returning an error instead? would it even be an error, or just a non-zero exit code indicating 'nothing went wrong, but theres nothing for me to show'?
