### ISSUE TITLE
GEOMETRY_INFO is surprising

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#292]
As mentioned by @mmathys and @myyc, seeing `user@host` when pressing enter, instead of just a clean newline is surprising.

How many people use the infoline? What do they use it for?

Should we remove the feature? 

Make it empty by default?

Highlight it in the documentation?

**Comment by mmathys** [comment]
IMO make it empty by default and highlight the feature in the docs would be the best solution.

**Comment by alxbl** [comment]
I also think it would make sense for `INFO` to be empty by default so as to have a well-known behavior.
