### ISSUE TITLE
git init produces an error: fatal: ambiguous argument 'HEAD'

### ISSUE THREAD

**Issue by russmack** [frmendes/geometry#305]
**Describe the bug**
`git init` produces:
`fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.` 
Other (all?) git command produce the same.

**To Reproduce**
1. Type `git init`
2. See error

**Expected behavior**
No error.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Git Version 2.30.0
 - Geometry version: latest a8033e0

**Comment by lox** [comment]
This happens whenever there isn't a commit in the repo, the relevant line is https://github.com/geometry-zsh/geometry/blob/main/functions/geometry_git#L31. 

I think it should be `git diff --quiet` vs `git diff-index --quiet HEAD`.

**Comment by jamescostian** [comment]
Resolved by #304
