### ISSUE TITLE
geometry swallows output without trailing \n

### ISSUE THREAD

**Issue by itsxaos** [frmendes/geometry#306]
Command output lacking a terminating newline gets overwritten by the prompt

![2021-02-08×11:15:46](https://user-images.githubusercontent.com/33079230/107206612-8e4e3880-69ff-11eb-9414-6699126b95ae.png)
Screenshot: default zsh prompt first, then geometry

The default zsh prompt adds the newline when it's missing (marked by the inverted `%` ), but unfortunately this not only does not work with geometry, it also "swallows" the output, overwriting it with the prompt.
The output does show up very briefly, but the prompt overwrites it.

I also tested it with `GEOMETRY_PROMPT=(geometry_newline)` but that does not help, it overwrites the output with an empty line.

**To Reproduce**
`echo -n "Test123 :^)"`

**Tested on**
Archlinux, with Alacritty and xfce4-terminal

**Comment by itsxaos** [comment]
I looked into this issue some more and it seems to be an issue with [marlonrichert/zsh-snap](https://github.com/marlonrichert/zsh-snap) and its `znap prompt`. It does not occur when I source `geometry.zsh` normally.
Sorry about that!

**Comment by torarnv** [comment]
In my case this was due to having `unsetopt prompt_s` in my configuration.
