### ISSUE TITLE
`git init` causes last commit to be 17121days

### ISSUE THREAD

**Issue by tomspeak** [frmendes/geometry#33]
![](https://d3vv6lp55qjaqc.cloudfront.net/items/3M3D3U3s2b362M1S3q40/Image%202016-11-16%20at%2010.24.25%20am.png)

To reproduce:

1. Create a new folder
1. `git init`

**Comment by frm** [comment]
It's the epoch timestamp conversion.

This happens because when the repo is created, [the last commit time](https://github.com/frmendes/geometry/blob/master/geometry.zsh#L110) is set to 0 so the displayed value is the current unix epoch timestamp.

**Comment by tomspeak** [comment]
Interesting, any quick fix? That being said, it's such a minor issue that you only see once every few months, for a few seconds. Was just making sure it wasn't anything more malicious than epoch being epoch!

**Comment by desyncr** [comment]
It should be easy to check for `last_commit` being `0`. Should we remove the invalid information blocks? (`prompt_geometry_git_time_since_commit`, `prompt_geometry_git_remote_check`).

**Comment by frm** [comment]
I'm not sure what I would like to display here. Maybe just `branch :: ⬡/$DIRTY_SYMBOL`? Or a message saying `no commits`. Any takes on this?

**Comment by tomspeak** [comment]
Some form of indication that there are no commits would be great. Open to `no commits` or a symbol.

**Comment by desyncr** [comment]
Should be an easy fix. Everybody's welcomed to take up this task. Otherwise I'd be up to do it.
