### ISSUE TITLE
RFC: Plugin architecture

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#42]
There are lots of tools that can be added to the prompt, they are useful for some but not generally useful for everyone, naturally. This causes the code to grow large and maintenance becomes a problem. This will become an issue as more prompts are added.

To be able to manage this issue I propose to turn most informative prompts (git, virtualenv, python, etc) into a separate file that can be loaded at runtime. This will keep separate the base prompt from the informative prompts, making maintenance a bit easier. Also performance-wise seems reasonable to keep unloaded unused prompts.

This structure will also provide the ability to create custom -user made- prompts, outside the geometry code base.

Implementation will require to establish a common interface for the prompts (function and variable names) as well as a globally available array to register a given plugins/prompt. Similar to https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md

Thoughts?

Edit: Probably Fixes #24

**Comment by frm** [comment]
I like this idea. It's starting to become difficult to maintain and the original idea behind geometry was trying to keep it minimal. I'd rather have a clean option with sane, minimal defaults and try to remove the unused code overhead.

What's your take on option flags? For example the git conflict count. Would it still be set by an environment variable?

**Comment by desyncr** [comment]
Yeah, I think so. All plugin-related environment variables will be defined -set up, defaults etc- in the plugin code, thus will be, sort of, invisible to geometry.

**Comment by frm** [comment]
I'm definitely up for this. There are a few things we would need to decide though:

- [ ] define minimal features
- [ ] define plugin function API
- [ ] define naming guidelines (function, variables and option flags)

**Comment by desyncr** [comment]
As Minimal features:
  - Ability to load informative prompts at run time (git, virtualenv, docker)
  - Ability to load custom prompts

Plugin interface:

    # One-time only function to setup plugin configuration variables
    # and register with geometry as a plugin
    geometry_prompt_<plugin_name>_setup

    # Prompt rendering function
    geometry_prompt_<plugin_name>_render

    # These probably belong to the plugin itself rather than geometry
    GEOMETRY_PROMPT_<plugin_name>_ENABLED (?)
    GEOMETRY_PROMPT_<plugin_name>_COLOR (?)

On the `geometry_prompt_<plugin_name>_setup` function the plugin will register itself with geometry as a plugin as follows:

    geometry_prompt_<plugin_name>_setup () {
        geometry_plugin_register <plugin_name>
    }    

On `geometry_prompt_<plugin_name>_render` it will render itself, probably already colorized. Returning the final result.

Naming guidelines could be as simple as:

    `geometry_prompt_<plugin_name>_*` for functions, and `-geometry_prompt_<plugin_name>_*` for "private" functions.

    `GEOMETRY_PROMPT_<plugin_name>_*` for configuration variables/flags.

Prompt rendering order will depend on the registration/loading order, so it'll be fully manipulable by the user.

I'm probably missing something out, but that's an initial attempt.

**Comment by frm** [comment]
I'm fine with the `setup/render` approach. The function and variable naming goes with what we already have set up. I'm finishing a README draft that can include those recommendations for contibuting.

A couple more topics:

How would you implement the plugin file sourcing by geometry?

What would the register function do, internally?

What would be the core of geometry? I'm inclined to just use the theme with async properties.

I also think we should have a `plugins/` directory, containing a directory per plugin with `<plugin>.zsh` and a `README.md`

**Comment by desyncr** [comment]
> How would you implement the plugin file sourcing by geometry?

In geometry's own setup function it'll iterate over the registered plugins and try to load the plugin by naming convention from geometry's own plugins: `$GEOMETRY_ROOT/plugins/geometry_prompt_<plugin_name>.zsh` 

Custom plugins will be sourced by the user after geometry:

    source geometry.zsh # Will load default plugins: git, virtualenv etc
    source custom_geometry_prompt.zsh # will register itself with geometry

To enable/disable default prompts:

    GEOMETRY_PROMPT_DEFAULT_PROMPTS=(git virtualenv etc) 

Before sourcing geometry.

> What would the register function do, internally?

It will add the plugin name to the registered plugins' array. Probably pre-formatting the prompt to keep performance reasonable.

> What would be the core of geometry? I'm inclined to just use the theme with async properties.

Agreed. Most rprompt functions should be default plugins with git enabled by default.

> I also think we should have a plugins/ directory, containing a directory per plugin with <plugin>.zsh and a README.md

Agreed.

**Comment by desyncr** [comment]
I'm also thinking `shutdown` and `unregister` functions.

BTW these changes can be fully backward compatible if we choose to load all default plugins by default and let them choose to be rendered or not (`setup` could return a flag to further be registered or not).

**Comment by frm** [comment]
I like that the plugins get a `setup` function but if geometry will be iterating over the global array and the plugins will always be in the default directory, do they still need to register with geometry? The way I see that would be if it was a custom plugin that isn't bundled with geometry.

**Comment by frm** [comment]
Can you elaborate on the `shutdown` function?

**Comment by desyncr** [comment]
Geometry itself will register the default plugins from `GEOMETRY_PROMPT_DEFAULT_PROMPTS` array in the `setup` function. Instead of registering they could be sourced, but I'd prefer to use the plugin interface.

The `shutdown` function will be defined, if needed, by plugins in order to call `unfunction`, remove variables, hooks etc. Probably called on the `unregister` function, used to remove informative prompts at run time.

**Comment by frm** [comment]
I'm fine with using the interface.

However, I think this work should start in a separate branch and break backwards compatibility. Most of the current option flags should be set aside to an external plugin and leave only some defaults like git and async, as well as the prompt symbol/colors customization. I really like the idea of stripping down the prompt in order to get it minimal and have it grow according to the needs of each developer, not having a lot of defaults. We can bundle a bunch of plugins with the prompt to be set if the user wants to.

**Comment by desyncr** [comment]
Fine. I'll create a feature branch today and sketch the minimal working version, we'll move from there.

**Comment by frm** [comment]
Cool. We can leave this issue open for future reference and for anyone to jump in and give their opinion, but we should probably keep PRs open to accompany progress and make decisions as they come up.

**Comment by desyncr** [comment]
I'll leave this issue open for general discussion and feedback while keeping most technical details/implementation discussion on a PR.

**Comment by frm** [comment]
Once #45 gets merged, the new plugin architecture will be implemented. However, as you mentioned, there are still a couple of things remaining. Off the top of my head:

- [x] README (on it)
- [x] Add a README with documentation for each plugin
- [ ] Compile step of default plugins into geometry (not necessary for 2.0, just a nice to-have)
- [ ] Complete config for custom separator (some plugins still use default `::` as far as I could tell)
- [ ] Enforce naming conventions
- [ ] Left prompt customization

**Comment by desyncr** [comment]
Alright. I'll be creating github issues for the point listed above. We can move from there.

**Comment by desyncr** [comment]
I'm closing this up as plugin structure is already set up and deployed. Missing/pending points have their own [issues](https://github.com/frmendes/geometry/issues) to keep track of them.
