### ISSUE TITLE
Set title doesn't work as expected

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#44]
When executing a long-running command the terminal title is set to "$COMMAND @ $CURR_DIR". Should it be the running command.

![screen shot 2016-12-01 at 6 02 19 pm](https://cloud.githubusercontent.com/assets/1857707/20812440/5da3da7a-b7f0-11e6-8cf6-de84b5d7cf6b.png)

Should be an easy fix for anybody interested in contributing.

**Comment by aishpant** [comment]
I am interested in working on this issue! But I have not been able to reproduce it.
Could you help me out here?

**Comment by desyncr** [comment]
Sure thing. As soon as I can I'll give you further information (OS, terminal etc).

**Comment by desyncr** [comment]
OS: OS X Yosemite, 10.10.5
Terminal: iTerm2 Build 3.0.12 & Terminal.app Version 2.5.3 (343.7)
zsh: zsh 5.3 (x86_64-apple-darwin14.5.0)

Anyways, it happened with zsh 5.2 as well, probably with other versions too.

**Comment by desyncr** [comment]
Step to reproduce:
  - Open a terminal
  - Run `sleep 10`

Expected results:
   - Terminal window title should display: sleep @ ~/path/to/current/directory

Results:
   - $COMMAND @ $CURR_DIR

Hope that helps!

**Comment by frm** [comment]
By the way, it's currently working on my end.

![screen shot 2016-12-16 at 12 26 26](https://cloud.githubusercontent.com/assets/4325027/21262756/e7514f28-c38a-11e6-95ac-180b24936725.png)

It's iTerm nightly, by the way.

**Comment by aishpant** [comment]
Works on my end too.
OS : macOS Sierra, 10.12.1
Terminal : Default terminal
zsh 5.2 

I'll try on iTerm2.

**Comment by frm** [comment]
@desyncr can you check if in the iTerm Preferences, under the Appearance tab, is there any option clicked on "Window & Tab Titles"?

**Comment by frm** [comment]
Also, don't forget to check the "Terminal may set tab/window title" option under Preferences > Profiles > Terminal. Probably should add that to the docs.

**Comment by desyncr** [comment]
May be I'm missing something, but remember it also does seem to work on Terminal.app.

![screen shot 2016-12-16 at 9 38 41 am](https://cloud.githubusercontent.com/assets/1857707/21263108/a4154a14-c373-11e6-9e58-d30fd5552cd8.png)

![screen shot 2016-12-16 at 9 39 03 am](https://cloud.githubusercontent.com/assets/1857707/21263109/a415af18-c373-11e6-959f-5edea6ea88b5.png)

**Comment by frm** [comment]
Works on Terminal.app here as well.

**Comment by frm** [comment]
macOS 10.12.1, zsh 5.3 (x86_64-apple-darwin16.1.0)

**Comment by desyncr** [comment]
I guess then it's my set up in some way messing up with this. I'll take a look later today.

@aishpant It'll be better to look for [other issues](https://github.com/frmendes/geometry/issues?q=is%3Aissue+is%3Aopen+label%3Aeasy) if you can't reproduce this one.

**Comment by desyncr** [comment]
It seems it's all about [this single line](https://github.com/frmendes/geometry/blob/master/geometry.zsh#L44) (check the single quotes). Not sure why you can't reproduce it thought.

**Comment by desyncr** [comment]
@aishpant  Are you up for this still? Let me know 👍

**Comment by aishpant** [comment]
@desyncr sorry I haven't seen the issue here yet. I'll take something else.

**Comment by desyncr** [comment]
Alright, I'll let  it hang out a bit more for anyone interested and then take it if there is no one to look after it.

**Comment by cnguy** [comment]
Hello, again! :) Just wanted to let you know that it works properly on my build and on both terminals as well.

El Capitan 10.11.6
zsh 5.0.8 & zsh 5.3.1 (one was an old built-in zsh, the other one is the updated one from homebrew)
Terminal.app 2.6.1
iTerm 2 3.0.12

Maybe a yosemite bug or something?

**Comment by desyncr** [comment]
Could anybody try:

    zsh -f
    source /path/to/geometry/geometry.zsh
    sleep 5

and check if the title is updated as expected? For me what happens is I see `$COMMAND @ $CURR_DIR`.

**Comment by frm** [comment]
Able to reproduce that way:

![screen shot 2016-12-23 at 12 37 10](https://cloud.githubusercontent.com/assets/4325027/21453998/a9ef8faa-c90c-11e6-98da-616827d6381d.png)

**Comment by desyncr** [comment]
It seems we're not properly setting `PROMPT_SUBST`. [print](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html) documentation. [Prompt expansion](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Prompt-Expansion) docs.

We probably should do `setopt PROMPT_SUBST` to make it work as expected anywhere.

**Comment by frm** [comment]
@ChauTNguyen @aishpant any of you want to tackle this?

**Comment by cnguy** [comment]
I'll try it. Where should `setopt PROMPT_SUBST` be placed though (for style purposes). Right now I have it under Misc configurations (line 35 of geometry.zsh).

**Comment by desyncr** [comment]
I think it belongs inside the set up method `prompt_geometry_setup` below [this line](https://github.com/frmendes/geometry/blob/master/geometry.zsh#L83). As the global configuration section in `geometry.zsh` is meant for global variables, very little actual code show be placed there.

**Comment by desyncr** [comment]
Fixed in #74
