### ISSUE TITLE
Left prompt customization

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#51]
- Modify prompt to make use of plugins
- Be able to configure plugins for rprompt as well as prompt.
- Evaluate which customization can be added

**Comment by desyncr** [comment]
One option to add would be to be able to configure pwd as one of the following:

- Only last dir name: ` ▲ /path/to/geometry` -> `▲ geometry`
- Folded path: `▲ /path/to/geometry/` -> `▲ /p/t/geometry`
- Full path (default)

First thing to do would be to move `prompt` as a plugin.

Making `prompt` a plugin I think it's a good move as it'll give users a chance to customize it or even completely change it. Adding more built-in configurations is something I'd like to avoid.

@frmendes Thoughts?

**Comment by frm** [comment]
I'd move `prompt` to a plugin, definitely. Really like the flexibility it gives for users to customize. Not a fan of `pwd` configuration. Lets face it, the only thing `prompt` would be showing is the directory. Well, symbol as well, but that's configurable.

If we're allowing pwd configuration might as well allow users to completely switch out the left prompt.
