### ISSUE TITLE
Remove "enabled" flag for plugins

### ISSUE THREAD

**Issue by frm** [frmendes/geometry#54]
Some plugins, such as docker machine, have an `enabled` variable. If the plugin is loaded, it should be considered enabled, otherwise the user wouldn't have added it to the plugin list.

It's also not intuitive having to add the plugin to a plugin list and setting an environment variable.

**Comment by desyncr** [comment]
It think most built-in plugins have a `*_ENABLED` configuration variable available.

It should be an easy fix for anybody interested.
