### ISSUE TITLE
Add Node/yarn version plugin

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#57]
Create built-in plugin (in the lines of `virtualenv` and `docker_machine`) for `node` and `npm` version prompt.

Prompt should look something like:

    ⬡ v6.9.2 (3.10.9)

`npm`s start up time is quite noticeable so version information should be cached in the setup phrase, in fact, this should be done for `node` and `npm`.

This is a great opportunity for anyone interested in contributing.

**Comment by castellanprime** [comment]
Hi. First time contributor here. Machine is Debian 8. Could I take this issue?

**Comment by desyncr** [comment]
Hi @castellanprime Sure thing. Go ahead and ask any question you have :+1:

**Comment by castellanprime** [comment]
So is it in the same format as docker-machine and virtualenv?

**Comment by desyncr** [comment]
It should be done in the form of a [plugin](https://github.com/frmendes/geometry/tree/master/plugins#plugins), the format should be:

    ⬡ v6.9.2 (3.10.9)

We're open to suggestions on what to show. I'm not a node developer so I initially proposed the format above, but if there is other more useful information to show, go ahead.

My suggestion is to first start with the plugin structure (setup/render methods) and little more than that. Once you get this done then add in the `render` method a basic `echo $(node -v)` and we'll move from there :)

**Comment by castellanprime** [comment]
Okay. Doing that now.

**Comment by castellanprime** [comment]
What is the version number inside the brackets?

**Comment by desyncr** [comment]
Should be `npm --version` IIRC.

**Comment by frm** [comment]
It's the npm version but I'd recommend supporting [yarn](https://yarnpkg.com/) when a `yarn.lock` is present.

**Comment by castellanprime** [comment]
Should we also support nodeenv and nvm as well? I installed node using nvm.

**Comment by desyncr** [comment]
I guess we can add a prefix if the active node version is from nvm.

With nvm installed:

    ⬡ nvm: v6.9.2 (3.10.9)

vs without nvm:

    ⬡ v6.9.2 (3.10.9)

No need for `nodeenv` for now.

Don't try to add every single tool available, with a basic plugin running that's enough, we can further improve it later on :)

**Comment by castellanprime** [comment]
Okay. I can print the versions but I have to add some code to detect whether the node is from yarn or from nvm.

**Comment by desyncr** [comment]
I'd suggest to push your working code and making a PR, that way we can start the code review and testing it out.

**Comment by castellanprime** [comment]
Okay. Doing that now

**Comment by castellanprime** [comment]
Should I tag the commit or not?

**Comment by desyncr** [comment]
No need  to tag. Just branch off master.

**Comment by castellanprime** [comment]
So I am going to repost the example I am working on:

My inital approach is to check for the following, in order in any directory the user is in:
(a) a yarn.lock file
(b) an .nvmrc file
(c) (possibly) a nodeenv.env file

The test could go like this, 

1. If (a) is found, then check for yarn in the `commands` array. If found, check `yarn version` . Else

2. If (a) is not found, then check if $NVM_DIR is set. If it is set, then check current directory for an .nvmrc file. If an .nvmrc file is found, then check if it is empty. If it is not, check if the first line matches the  output of command `nvm current`

A first shot at this is shown in the picture below:
![screenshot from 2017-01-23 22 58 29](https://cloud.githubusercontent.com/assets/15849318/22312298/e63b1090-e31c-11e6-9744-23c293773799.png)

Is the test 
`if [[ -e yarn.lock]] || [[ -f .nvmrc && -r . nvmrc && -n "$(head -1 .nmvrc)" ]]`
a good start? What do you suggest?

**Comment by desyncr** [comment]
Not very familiar with nvm and yarn, so my questions may sound silly:

- Why check for `$NVM_DIR`? -- we seem to look for `.nvmrc` in curren directory after all
- In which case `.nvmrc` may be empty? -- I assume if it exists, there's something on it
- Why check `nvm current` matches `.nvmrc`?

**Comment by desyncr** [comment]
@castellanprime Are you up to implement node/yarn?

I hope we can get you on board since you implemented node plugin! :) It'll be quite a differentiator from other prompts.

**Comment by castellanprime** [comment]
@desyncr @frmendes I am very sorry for not doing much work on this. Had exams last week. Also I have been trying to install node with yarn for the last couple of minutes with no luck. I guess that I cannot get the version of node from yarn. Nvmrc can get multiple node versions if installed on the system but yarn might not be able to.

**Comment by desyncr** [comment]
@castellanprime No worries! :+1: Gonna take a look at yarn later to see if I can be of any help.

**Comment by castellanprime** [comment]
Is this what you want? 
![screenshot from 2017-02-06 20 33 04](https://cloud.githubusercontent.com/assets/15849318/22675485/9c03036e-ecab-11e6-99bd-ee7e2e6ab110.png)

**Comment by desyncr** [comment]
Zsh offers a simpler way to populate an array of files but yeah I think it's a good approach.

**Comment by castellanprime** [comment]
@desyncr I am having some problems running the example I showed. So I make the modification to the array that you commented on. The code is shown below:

![screenshot from 2017-02-07 16 19 01](https://cloud.githubusercontent.com/assets/15849318/22714244/37b98f26-ed51-11e6-860d-61c7d4362917.png)

I tested the piece of code with (zsh -x ):
![screenshot from 2017-02-07 16 22 29](https://cloud.githubusercontent.com/assets/15849318/22714339/a69556fa-ed51-11e6-8cbf-4cd8273f4821.png)

Could you offer some guidance to how I should proceed? Thanks

**Comment by desyncr** [comment]
Looking good. Go ahead and create a PR. :+1:

**Comment by desyncr** [comment]
Merged in #108
