### ISSUE TITLE
Add Ruby/rvm version plugin 

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#58]
Similar to #57 create a plugin for ruby/rvm version information prompt.

Use `rvm`/`rbenv` if available. Display in the following format:

     ◆ 2.3.3 (1.27.0)

Cache version information in the setup phrase.

This is a great opportunity for anyone interested in contributing.

**Comment by frm** [comment]
I have a set up ready for this, might merge if no one else wants to tackle it.

**Comment by reuben453** [comment]
Hi, I'd like to give this a shot. Can I take this issue?

**Comment by reuben453** [comment]
It will probably be useful if the current rvm gemset is also displayed. What do you think?

**Comment by desyncr** [comment]
@reuben453 I'd have it under a configuration variable, something like:

    GEOMETRY_RUBY_RVM_SHOW_GEMSET=[true|false]

Good work so far in #93

**Comment by reuben453** [comment]
Should this be closed now?

**Comment by frm** [comment]
@reuben453 you're right, closing.
