### ISSUE TITLE
Spaces before git plugin's branch name

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#61]
There are a few empty spaces before git branch name. There should be a single space between the plugin outputs (in this case exec_time and git).

![screen shot 2016-12-13 at 1 15 29 pm](https://cloud.githubusercontent.com/assets/1857707/21148226/550a1de4-c136-11e6-90a1-748c6d2becad.png)

For anyone interested in their first PR.

**Comment by vincecampanale** [comment]
I'd be happy to give this a shot. (I'm new)

**Comment by desyncr** [comment]
Please go ahead. Don't be afraid to ask any question. We'll given you feedback as soon as we can.

**Comment by vincecampanale** [comment]
Sounds good. Couple of questions: How should I begin? Fork and get a local version up and running? Is there a troubleshooting/development mode?

**Comment by desyncr** [comment]
@vincecampanale Currently we don't have a debug/verbose/development mode. It would be a nice addition I think 👍  So we'll keep that in mind.

There is some documentation about how we manage [plugins](https://github.com/frmendes/geometry/blob/master/plugins/README.md) and prompts that may help you with this.

For a start do [fork](https://help.github.com/articles/fork-a-repo/) and clone your fork locally:

    git clone git@github.com:vincecampanale/geometry.git

Do create a bugfix branch to work on (a common practice):

    git branch -b bugfix-git-prompt-spaces

When developing what I do is configure geometry theme simply by sourcing it this way:

   `~/.zshrc`:

    source /path/to/geometry.zsh

Then hack, open a new terminal/tab/panel, check and repeat.

Finally, when you see your changes working, do push your changes to github and make a PR:

    git push -u origin bugfix-git-prompt-spaces

You should see a "Make Pull Request" button (or similar wording) on the Github web interface.

We'll review the changes, test them on various configurations (pretty much like you would) and provide as much feedback as you'd need.

**Comment by vincecampanale** [comment]
Okay, forked and cloned. Currently familiarizing myself with the code. What exactly is zsh? From my Googling I've found that it's kind of a Terminal application that does more than just standard Terminal. How do I enable zsh in my terminal and set it to 'geometry' mode. I added a line `source ~/directories/to/geometry.zsh` to `~/.zshrc` but Terminal hasn't changed. I'd like to get used to using the application in order to contribute more.  Also, what language is this written in? "ZSH" language?

**Comment by desyncr** [comment]
@vincecampanale Take a look [here](https://wiki.archlinux.org/index.php/Zsh). It'll give you a general understanding of what is and what it can do, how to set it up and [configure](https://wiki.archlinux.org/index.php/Zsh#Configure_Zsh).

[Here](https://gist.github.com/desyncr/528b1df109d6711ba4a0ae4f1447cb08) is the minimal working `.zshrc`.

Depending on your OS you have various options to install zsh:

    Debian/Ubuntu: apt-get install zsh

    Fedora/Cent OS: dnf install zsh

    Mac OS: brew install zsh

You can permanently switch to `zsh` with:

    chsh -s `which zsh`

You don't need to but if you spend some time in the terminal you may find it a good option to check.

Let me know if you can get it working.

**Comment by vincecampanale** [comment]
I'm getting `chsh: /usr/local/bin/zsh: non-standard shell`. There is a line already in my .zshrc `export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting`. Could that be affecting it?

**Comment by vincecampanale** [comment]
Oh wait nevermind. Just restarted terminal and it appears to be working.

**Comment by vincecampanale** [comment]
Thanks, it's working! 
Now, how can I get exec_time to show? What kind of action prompts the display pictured in the issue above?

**Comment by desyncr** [comment]
The built-in exec_time plugin is enabled by default. So you don't need to configure anything.

What it does is that if a command's execution duration is above certain threshold it's displayed as shown in the screenshot.
The default threshold is 5 (seconds). So issuing this simple command wound render exec_time:

    sleep 5

Hope that helps.

**Comment by desyncr** [comment]
@vincecampanale Correction. There is still a configuration variable you'll need to set up:

    PROMPT_GEOMETRY_EXEC_TIME=true

Put that line _before_ sourcing geometry.

I thought this was removed in [this issue](https://github.com/frmendes/geometry/issues/54).

**Comment by desyncr** [comment]
@vincecampanale Are you stuck or need any other kind of feedback? Let us know.

**Comment by vincecampanale** [comment]
Yea, I'm having difficulty with troubleshooting. I'm also getting this error 
![screen shot 2016-12-21 at 1 34 08 am](https://cloud.githubusercontent.com/assets/15335197/21379556/e8d4f616-c71c-11e6-925b-efdc8ad4fba5.png)

The relevant lines of code: 
<img width="431" alt="screen shot 2016-12-21 at 1 34 43 am" src="https://cloud.githubusercontent.com/assets/15335197/21379566/fc380004-c71c-11e6-8a77-8da4793aea4f.png">

Any thoughts on a good place to start? I guess I'm just getting used to the new programming language and application type. I've never worked with zsh or any kind of terminal/shell application before.

**Comment by desyncr** [comment]
A first look nothing seems out of place. You may create a [gist](gist.github.com) with the relevant file so it's easier to look at.

**Comment by desyncr** [comment]
Closing this as per #71. Thank you @vincecampanale
