### ISSUE TITLE
Aliased commands may break geometry

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#63]
As per https://github.com/frmendes/geometry/issues/59. Aliased commands may break/change geometry inner workings.

Avoid this with a similar approach to https://github.com/zsh-users/zsh-syntax-highlighting/issues/390:

At the top:

    # Save aliases into a variable and remove/unalias everything
    zsh_highlight__aliases=`alias -L`
    builtin unalias -m '*'

At the bottom:

    # Restore aliases & kill global variable
    eval "$zsh_highlight__aliases"
    builtin unset zsh_highlight__aliases

**Comment by frm** [comment]
As I mentioned in #59 looking through the code there don't seem to be many instances of possible aliased commands.

A possible solution would be prepending with `command rm` or `\rm`, even though that makes the code messy.

Unaliasing and aliasing over and over is going to affect render time, isn't it?

**Comment by desyncr** [comment]
I guess this issue was left hanging out since this issue was resolved with `\rm`.
