### ISSUE TITLE
Gracefully handle `--ignore-submodules` flag missing in git 1.7.1 and below

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#69]
`--ignore-submodules` flag was introduced in git `1.7.2`. If geometry is used with this git version it throws an error:

```sh
▲ ~/geometry error: unknown option `ignore-submodules'
usage: git status [options] [--] <filepattern>...

    -v, --verbose         be verbose
    -s, --short           show status concisely
    --porcelain           show porcelain output format
    -z, --null            terminate entries with NUL
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)
```

This is almost a non-issue as git `1.7.1` was released in 2010, but I stumbled with this issue on a CentOS 6 machine.

**Comment by frm** [comment]
Well, we can always fallback to the previous, single-step method, can't we?

**Comment by desyncr** [comment]
It's not related to #68 as the flag `ignore-submodules`  was present since awhile I think.

**Comment by frm** [comment]
Did you feel the need to use v1.7.2?

According to [this](https://github.com/git/git/releases/tag/v1.7.2) git v1.7.2 was released in July 2010. It's over six years old, I'm not sure we want to have a mechanism to support software that is barely in the wild.

**Comment by desyncr** [comment]
Not really, I just stumbled with a machine with Cent OS 6. I do agree it's too much of a troubled to handle this particular case.

Closing.
