### ISSUE TITLE
`exec_time` built-in plugin keeps on being displayed

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#72]
The `exec_time` built-in plugin shows a strange behavior after being displayed once. It may keep being show whether a command is executed or not.

Steps to reproduce:

- Launch terminal
- Wait at least 5 seconds
- Press Enter key

Expected behavior:

- No `exec_time` plugin is shown

Shown behavior:

- `exec_time` is shown (8s, 9s, etc)

**Comment by cnguy** [comment]
I think the cause of this is that there's no conditional check to see if a proper command was actually executed.

The first case is when I run `source geometry.zsh`, a timestamp is saved, and so running any command afterwards will output the elapsed seconds.

The other case is regarding blank inputs.

When I press enter with blank input in my terminal, `prompt_geometry_set_command_timestamp()` runs and a timestamp is saved.

Then, if I were to run another command, a new timestamp is saved, and `prompt_geometry_check_command_exec_time()` runs regardless of the last input (in this case, an empty input), and if the elapsed time > the max time, it unnecessarily outputs the elapsed seconds.
