### ISSUE TITLE
Unpushed changes symbol on branch without upstream tracking

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#81]
Not really sure this is the expected behavior or not, but on branches without upstream:

![screen shot 2016-12-30 at 5 52 38 pm](https://cloud.githubusercontent.com/assets/1857707/21572542/d8ba6498-ceb8-11e6-9e82-21e886274bcd.png)

This is shown on a repo without commits:

![screen shot 2016-12-30 at 5 55 22 pm](https://cloud.githubusercontent.com/assets/1857707/21572558/24c99dd6-ceb9-11e6-8fd2-2608a5bc3969.png)

**Comment by frm** [comment]
The second one is indeed a bug.

I had a local fix for the first one at one point in time but have since deleted it since I'm using it as a reminder to set the upstream. It's pretty convenient. Maybe set a different symbol for that?

**Comment by desyncr** [comment]
Yeah I agree  it's quite convenient. I'd go ahead and fix the second issue.

**Comment by desyncr** [comment]
I'm gonna fix it for real this time :) This is just a reminder.
