### ISSUE TITLE
Mercurial support?

### ISSUE THREAD

**Issue by ev-agelos** [frmendes/geometry#82]
Is it possible to be added? I really like geometry!

**Comment by frm** [comment]
I'm actually not sure. Personally, I've never worked with mercurial. @desyncr any thoughts?

You can easily create a [custom plugin](https://github.com/frmendes/geometry/blob/master/plugins/README.md) to try it out. Feel free to submit a PR if so.

**Comment by desyncr** [comment]
It can be easily added as a built-in plugin. Personally I'm worried about maintenance as I don't regularly use mercurial myself.

I would go with a minimal implementation if any (current branch, last commit, dirty/clean status).

**Comment by frm** [comment]
That's my issue as well. Not using mercurial means it will hardly be maintained.
