### ISSUE TITLE
Making geometry look like it is shown in the example images

### ISSUE THREAD

**Issue by ctian1** [frmendes/geometry#85]
In the example images, the colors and other configuration options are different from the default configuration geometry has. Is it possible for the exact configuration of the example to be explained somewhere, or at least some of the color choices? It looks awesome.

**Comment by desyncr** [comment]
Tried [these](https://github.com/frmendes/dotfiles/blob/master/system/prompt.zsh) settings?

**Comment by frm** [comment]
Yea, these are my personal settings. I thought I had disabled them when taking the screenshots.

You can just define the environment variables @desyncr linked and you should be all set.

Right then, @desyncr what's your take on this? Update the screenshots or update the default settings?

**Comment by desyncr** [comment]
I'd leave the default as they are now. No need to change them, I'd either:

- Add a FAQ entry pointing out this configuration
- Update the screenshots

I think the screenshots need some love:

- All of them are too tall with little content to show
- The first one is too noisy compared with the [previous version](https://github.com/frmendes/geometry/blob/b50b78cf0b24cc932fdf5fb12d18248af82775fa/screenshots/geometry.png)

**Comment by frm** [comment]
Agreed, I'll update them today.

**Comment by frm** [comment]
See #86. Closing this for now.
