### ISSUE TITLE
Clarify plugins used in screenshots

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#92]
Some users may assume that syntax highlighting will be enabled with the theme (command colouring)  - at least I got asked once.

So it may be useful to add a note explaining which plugins are used.

AFAIK there is only `zsh-users/zsh-syntax-highlighting` plugin installed in the screenshots.

Edit: Other thing to add would be the terminal and `rupa/z` plugin.

**Comment by frm** [comment]
Adding a question to the FAQ works, right?

**Comment by desyncr** [comment]
Yeah, that will work.

DC*
Sent from mobile.

**Comment by desyncr** [comment]
```
### My shell looks different to the screenshots. What is missing?

You may need `rupa/z` and `zsh-users/zsh-syntax-highlighting` plugins installed.

```

**Comment by frm** [comment]
Oh boy, I forgot about this. I'll updated when I get to my computer, which is probably tomorrow.
